### ISSUE TITLE
Crashing randomly and when emoting

### ISSUE THREAD

**Issue by kibbey4** [goatcorp/Dalamud#1031]
when using dalamud, even with 0 plugins installed, the game locks up randomly when using emotes, when someone else uses emotes, and sometimes when im not even doing anything

i've reinstalled the launcher and ff14 twice, tried the legacy injection method for dalamud, nothing has stopped the crashing

**Comment by Number2046** [comment]
Same issues and when useing IVCS emotes. Sometimes when just logging out. These happening since last update for the latest patch.

**Comment by kibbey4** [comment]
i dont even get an error, i get nothing useful to go off of

**Comment by Number2046** [comment]
Mine (and quite a few friends alll get the same issue and that page appears saying caused by other mod but it 1st happened when I had just Penumbra installed with no mods added. No other plugin just crash. That page comes saying it crashed.

**Comment by kibbey4** [comment]
i reinstalled windows and i dont crash anymore, who knows what was causing that
