### ISSUE TITLE
UI: after steam popup text unreadable

### ISSUE THREAD

**Issue by Natherul** [goatcorp/Dalamud#1047]
When starting the application through steam it first looks fine but after the steam message with access community bla bla. It looks like:

![image](https://user-images.githubusercontent.com/3688166/209304468-861bee03-792b-4cac-a445-9f15881cdf13.png)

Followed the guide https://goatcorp.github.io/faq/steamdeck

Although Im not on a steam deck but linux so I assumed it would be the same.
Operating System: Arch Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.1-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT
Manufacturer: ASUS

**Comment by NotNite** [comment]
This is the wrong repository to leave this issue on - https://github.com/goatcorp/XIVLauncher.Core
