### ISSUE TITLE
Dalamud "Wait for plugins before game loads" don't work properly

### ISSUE THREAD

**Issue by Grind3x** [goatcorp/Dalamud#1096]
Hello. I've just installed XIVLauncher and Penumbra on Steam Deck.
The checkbox with "Wait for plugins before game loads" is enabled.
In Penumbra setting checkbox "Wait for plugins on Startup" is also enabled.

But when I start the game, Penumbra is loading after a few seconds (~10-15 seconds).

**Comment by goaaats** [comment]
This doesn't work on Linux/Proton and probably won't in the foreseeable future. Nothing we can do about it directly.
