### ISSUE TITLE
File picker hangs game for several minutes on open

### ISSUE THREAD

**Issue by ascclemens** [goatcorp/Dalamud#1130]
I've mentioned this in Discord before, but this is becoming increasingly frustrating, so I figured I'd make an actual issue.

Unfortunately, I can't really offer reproduction steps beyond "open the file picker". Happens in Penumbra, for example, but I've confirmed it in various plugins. Open, the game hangs for several minutes, and eventually it comes back and works fine until you need to open it again.

Otter mentioned it may be due to unresponsive network locations and `Directory.Exists` when populating the sidebar, but all I have is one samba share. If that *is* the cause, surely it's better to have that hang when you click on the location versus every single time the damn window opens. It's definitely not feasible to ask users to change their network configuration for Dalamud, either.

This showed up roughly around 6.3.

**Comment by goaaats** [comment]
I looked into this a while ago and checked how other games do it, both osu and OpenRCT2 use GetLogicalDrives and both seem to have the same issue, at least I've read osu tickets of people complaining about this. Doesn't seem like there actually is a reliable way to check if a drive is present so maybe we should just not, and list all of them instead.

Been a few months so maybe osu has solved this now, if someone wants to have a look.

**Comment by karashiiro** [comment]
Just searched both ([1](https://github.com/ppy/osu/search?q=GetLogicalDrives), [2](https://github.com/OpenRCT2/OpenRCT2/search?q=GetLogicalDrives)) and neither seems to reference `GetLogicalDrives`.

**Comment by StevenPolley** [comment]
I have noticed this too with one of my network drives if my server is powered off.  It sometimes happens in Windows explorer too when it tries to enumerate my drives.  Using offline files (disgusting) seems to prevent it, or you can disconnect the drive and instead add it as a network location or just use a shortcut but you won't have a drive letter.

**Comment by ascclemens** [comment]
I have no network locations with a drive letter, only one Samba share, for what it's worth.
![image](https://user-images.githubusercontent.com/955250/221038459-bfd4c7d5-4f0a-46bd-9d66-2815638a28be.png)

**Comment by karashiiro** [comment]
Coming back to this, can we just toss this on a thread and populate the drive list asynchronously?

**Comment by ascclemens** [comment]
> Coming back to this, can we just toss this on a thread and populate the drive list asynchronously?

I don't see why not, this still makes any mod that uses the file picker unusable for me, as I have to wait 5-10 minutes for it to open.

**Comment by DeaLumi** [comment]
Per goaaats' request, going to replicate some of the information from my duplicate issue here:

[This stackoverflow post](https://stackoverflow.com/questions/1612408/system-io-driveinfo-getdrives-hangs-with-disconnected-network-drives) discusses (somewhat fatalistically) an issue with `DriveInfo.GetDrives()` (called by Dalamud's UI code [here](https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Interface/ImGuiFileDialog/FileDialog.Files.cs#L301)) hanging for extended periods in the presence of an unavailable network drive. (This is probably what [StevenPolley is seeing](https://github.com/goatcorp/Dalamud/issues/1130#issuecomment-1440730116).)

My hangs have ranged in the 20 - 40 seconds, and I've only had one crash which had something to do with a plugin doing something in the background during the hang. In my case, I can work around it by turning on my NAS or unmapping the drive, but it's not ideal. It's an extremely irritating issue, but I can understand why it wouldn't be a high priority -- it's an uncommon circumstance.

(I _am_ somewhat astonished, though, that the C# docs don't warn about the possibility of this call blocking for seconds to minutes. Seems like that would be important to mention...)

**Comment by NotNite** [comment]
Somewhat annoyingly, [the constructor for DriveInfo](https://learn.microsoft.com/en-us/dotnet/api/system.io.driveinfo.-ctor?view=net-7.0) doesn't take UNC paths, so even if we could somehow get a list of drives without this method, we can't include network drives in it.

I'm interested in trying to replicate this problem on my own machine; perhaps all I need to do is set up a Samba share and map it?

**Comment by karashiiro** [comment]
I have two Samba shares and barely notice the hitch (it's less than a second), so there's probably more to it than just having network locations. I'd guess that one or more of those shares needs to be extremely slow or unresponsive when `GetDrives` is called for this to be noticeable.

Either way, PR up, feel free to have a look.
