### ISSUE TITLE
Profiles in master

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#1180]
- [x] Make UI fancy
- [ ] Loc
- [ ] Error handling
- [ ] Testing
- [x] Import/Export(just needs UI support)
- [ ] Clean up commented out pre-profile code
- [x] Collapse command ops
- [ ] Maybe "conditions"? E.g. load profile when on a specific character.

**Comment by Aireil** [comment]
Issues found:
- Dev plugins with `Start on boot` turned off are not enabled when game starts. Probably should lock `Start on boot` if the plugin is part of a profile.
