### ISSUE TITLE
Add Happy Eyeballs to our HttpClient

### ISSUE THREAD

**Issue by KazWolfe** [goatcorp/Dalamud#1186]
The Discord has recently been absolutely flooded by users experiencing issues connecting to Kamori and other sites that use IPv6. Generally, this is caused by local ISP hiccups or other problems where a user's IPv6 connection is unstable. Our typical solution has been to tell users to enable a VPN or disable IPv6 entirely, neither of which are particularly _good_ solutions, especially as browsers don't have this problem. Enter: [Happy Eyeballs](https://www.rfc-editor.org/rfc/rfc8305).

While it would really be better for [Microsoft to do this](https://github.com/dotnet/runtime/issues/26177) for everyone and everything, it may make sense for us to just do it ourselves for now. Osu! [has an implementation](https://github.com/ppy/osu-framework/pull/4191/files) that we can look at borrowing as well.

The scope of this Issue is to ensure that Happy Eyeballs isn't already available in .NET (and just needs us to pass an argument somewhere), and if not, to borrow Osu's implementation (and others) for our own use case.

**Comment by KazWolfe** [comment]
TBD: Can we (should we?) create our own `HttpClient` that plugins can consume so that they, too, can enjoy Happy Eyeballs without copying a lot of unnecessary work?

**Comment by kalilistic** [comment]
For plugins using it, usually I set a defined timeout and default request headers. Might not work as well for a shared instance, but maybe could set those at the request level. Or the wrapper could handle it.

**Comment by goaaats** [comment]
We should either have it as a service or patch this behavior in with monomod by default. Probably the former, then reevaluate. If plugins want this they should switch to the service.
