### ISSUE TITLE
Provide way for plugins to know when Dalamud is done with updates

### ISSUE THREAD

**Issue by ascclemens** [goatcorp/Dalamud#1192]
Heliosphere auto-updates mods on login, but Dalamud can interrupt that and cause issues by updating Heliosphere while Heliosphere is performing its own updates.

A callback fired when all plugins are done loading post-update (or immediately if auto-updates aren't on?) would help.

**Comment by ascclemens** [comment]
How does this work for the case when auto-update was before plugin load?

**Comment by goaaats** [comment]
Gotcha, I figured you could do that via PluginLoadReason, but I guess that would be a little unreliable/timing-dependent if people are managing plugins on the title screen. Added another thing in https://github.com/goatcorp/Dalamud/commit/ca8a05b672b7622140bfbaeb1aa1392c49ea9209.

**Comment by ascclemens** [comment]
Perfect :sparkles:
