### ISSUE TITLE
Functions may be partially unhooked during Dalamud unload, leading to crashes/instability

### ISSUE THREAD

**Issue by nebel** [goatcorp/Dalamud#1236]
While investigating some crash dumps which ocurred at game shutdown, I noticed what seemed like something strange: a native game function was running with what appeared to be unsual, mangled instructions. The issue was inconsistent, but after some extensive debugging it seemed like instructions hooked by Dalamud were only being partially restored when Dalamud unloaded.

This eventually led me here: [HookManager.cs#L136](https://github.com/goatcorp/Dalamud/blob/5a8fff515fc93becd1f96b598da25ada88b3a65f/Dalamud/Hooking/Internal/HookManager.cs#L136)

When we try to remove the hook here, we currently do so by restoring the "original" bytes from the start of the hooked function until we encounter a byte which is unchanged. The problem, however, is that there is a small but not insignificant likelihood that any given byte in the "original" bytes may be the same as the corresponding hook byte in the same position. Because we stop as soon as a single byte is the same, we risk truncating our "restored" bytes.

Consider the following function which we want to hook:

```asm
(opcodes)
	48 83 79 28 00        - cmp qword ptr [rcx+28],00 { 0 }
	0F85 B5000000         - jne ffxiv_dx11.exe+1239050
	C3                    - ret
(bytes)
	48 83 79 28 00 0F 85 B5 00 00 00 C3
```

One possible valid hook for this function, and one which does *not* reproduce this bug is as follows:

```asm
(opcodes)
	FF 24 25 000B0800     - jmp qword ptr [00080B00]
	90                    - nop 
	90                    - nop 
	90                    - nop 
	90                    - nop 
	C3                    - ret 
(bytes)
	FF 24 25 00 0B 08 00 90 90 90 90 C3
```
	
Note that if we compare the byte sequence between this hook and the original function, every byte is different. However another equally valid hook which just so happens to jump to a different memory address is the following:

```asm
(opcodes)
	FF 24 25 D0000F00     - jmp qword ptr [000F00D0]
	90                    - nop 
	90                    - nop 
	90                    - nop 
	90                    - nop 
	C3                    - ret 
(bytes)
	FF 24 25 D0 00 0F 00 90 90 90 90 C3
```
	
The fifth byte in this hook is 00, the same as the original fifth byte. In this case, HookManager will generate a `snippet` of length 4, which when restored over the start of the hook, results in the following:

```asm
(opcodes)
	48 83 79 28 00        - cmp qword ptr [rcx+28],00 { 0 }
	0F00 90 909090C3      - lldt word ptr [rax-3C6F6F70]
(bytes)
	48 83 79 28 00 0F 00 90 90 90 90 C3
```

The left-over `lldt` will cause a native memory corruption exception if the function is called at any point after Dalamud has unloaded, which is quite likely to happen for functions called every frame for example.

By instrumenting the hooking process to detect these issues, I found while that the risk of this happening is small for any given hook, it is large enough to happen consistently when many hooks exist. With hook instrumentation active, for a random Dalamud load with 60 official plugins, I saw 111 "OK" hooks and 4 "MISMATCH" hooks. As an example (I believe these hooks were from SimpleTweaks):

```
[VRB] [OH] Trimmed 0x7FF68D9709D0: naiveLength=4 fullLength=10 <C:\goatsoft\companysecrets\dalamud\Hooking\Internal\ReloadedHook.cs> (HOOK-MISMATCH)
[VRB] [OH] Mismatch analysis:
[VRB] [OH]       Original: 48895C240848896C24104889742418574883EC30488BF9498BF1488B4910498BE88BDA488B01FF5030488BC88BD3E88DE942
[VRB] [OH]         Hooked: FF242500083A009090904889742418574883EC30488BF9498BF1488B4910498BE88BDA488B01FF5030488BC88BD3E88DE942
[VRB] [OH]   Naive Unhook: 48895C24
[VRB] [OH]    Full Unhook: 48895C240848896C2410
[VRB] [OH] Trimmed 0x7FF68DC6A0E0: naiveLength=4 fullLength=10 <C:\goatsoft\companysecrets\dalamud\Hooking\Internal\ReloadedHook.cs> (HOOK-MISMATCH)
[VRB] [OH] Mismatch analysis:
[VRB] [OH]       Original: 48895C24084889742410574883EC200FB68188010000410FB7F824140FB7F2488BD93C14750EB8FF0F0000668581B6010000
[VRB] [OH]         Hooked: FF242510083A00909090574883EC200FB68188010000410FB7F824140FB7F2488BD93C14750EB8FF0F0000668581B6010000
[VRB] [OH]   Naive Unhook: 48895C24
[VRB] [OH]    Full Unhook: 48895C24084889742410
```

Again, this is not necessarily consistent as it may depend on the hook's `jmp` location which changes each execution, so these are just examples.

To fix this issue, we likely need to check the hook data more extensively either at hooking or unhooking time. Currently (as you can see above) we store 50 original bytes and stop when we find a single left-to-right match. The "full" unhook technique I used above checks backwards from the last original byte, and does its analysis at hook time rather than unhook time.

I have opened PR #1237 containing one potential solution to this issue, and would be happy to address any feedback or concerns you may have.

Thank you.

**Comment by goaaats** [comment]
Merged the PR; thanks a bunch for sorting this out. Not really sure how we can observe/measure if the fix worked, so I might leave it to you to close this. Let me know if there's anything we can do.

**Comment by nebel** [comment]
I tested again on master after the merge and confirmed that a hook which would have previously been partially unhooked was fully unhooked and the unload crash was prevented. Based on that I'll close this issue. Thanks again for your testing and review.
