### ISSUE TITLE
[Wine] Discord.Net

### ISSUE THREAD

**Issue by cking** [goatcorp/Dalamud#135]
Wine installs .net4.8 in windows 7 mode
.net4.8 officially doesnt support websockets on windows 7 (and 8 as well for that matter)

to make websockets work on Windows 8 and lower (and thus wine) for discord.net, you have to install an alternative websocket provider.

Discord.net provides one such websocket provider: https://www.nuget.org/packages/Discord.Net.Providers.WS4Net/
Here would be an example how to use it: https://github.com/discord-net/Discord.Net/blob/322d46e47b47e44f8b62b1ddcdcf39280cac6771/docs/guides/getting_started/samples/netstd11.cs#L7

This is the dalamud.exe log throwing a platform not supported exception:
https://zerotsu.z0ne.moe/share/dalamud.txt

**Comment by reiichi001** [comment]
Hello!

Wanted to check if this is still an issue with the current Dalamud.DiscordBridge plugin, which has replaced the discord bot formerly in Dalamud.

**Comment by daemitus** [comment]
No response, no update, no problem.
