### ISSUE TITLE
Add row copy to log window

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/Dalamud#1362]
Right now the log window has a single copy button. It'd be nice to be able to copy a single row to the clipboard.

**Comment by kalilistic** [comment]
discussion on discord with some options: https://discord.com/channels/581875019861328007/653504487352303619/1149800951050424440

**Comment by MidoriKami** [comment]
Completed in: 08fd4434eaae56d7dae7b6dbdbf7263eb5b0ded0
