### ISSUE TITLE
Injector: when args more than 1, the pid(arg[0]) will not be used

### ISSUE THREAD

**Issue by FairyScript** [goatcorp/Dalamud#137]
https://github.com/goatcorp/Dalamud/blob/7481972915297236b83342cc02499e82b1fbff9d/Dalamud.Injector/Program.cs#L35-L38

If this is not intentional, I'll push a PR to fix it.
d4b5262b285bee830834d39581b1b31c9fd15e5d

**Comment by goaaats** [comment]
Thanks! Was actually wondering about this, someone reported that issue before.
