### ISSUE TITLE
Logging prefix overload

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/Dalamud#1375]
Logging (including the new version) has a private method using Assembly.GetCallingAssembly(). Could an overload be added to allow specifying the name instead of this? Would be cleaner for multi-assembly plugin solutions.

I'm happy to raise a PR if this sounds ok.

**Comment by MidoriKami** [comment]
I feel this should be documented here:

![image](https://github.com/goatcorp/Dalamud/assets/9083275/28b0d5c3-7ad2-4bf9-94b6-8a8da87120c8)

**Comment by KazWolfe** [comment]
I'm going to close this issue in favor of API 9's logging updates. The log prefix will be set to the InternalName of the plugin requesting the service.

It will, unfortunately, be the responsibility of the developer to properly manage passing the created log object(s) around accordingly.

If API 9's solution does not address this issue, re-open this and let us know why so we can figure out a better solution.
