### ISSUE TITLE
Size of World

### ISSUE THREAD

**Issue by Bluefissure** [goatcorp/Dalamud#151]
I think the size of currentWorld and homeWorld should be `ushort` instead of `byte` at [Actor.cs#L71](https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/ClientState/Structs/Actor.cs#L71).
You can see [World.csv](https://github.com/xivapi/ffxiv-datamining/tree/master/csv/World.csv) for ref.

**Comment by Caraxi** [comment]
It can't be because theres no room for a short there

**Comment by Bluefissure** [comment]
> It can't be because theres no room for a short there

`CurrentWorld = 0x1884` and `HomeWorld = 0x1886`, why theres no room for a 2-byte `ushort`?

**Comment by Caraxi** [comment]
Yep I'm an idiot and didn't see offsets on the line so just assumed it was sequential and didn't notice it was definined with a constant lol

**Comment by goaaats** [comment]
Thanks for fixing this!
