### ISSUE TITLE
Issues with the anchor point on Server Info Bar.

### ISSUE THREAD

**Issue by Annullare** [goatcorp/Dalamud#1524]
When the character count or total length changes in Server Info Bar, the frame undergoes a length adjustment with the center anchored at the last confirmed position. When I toggle the UI settings, it seems that Server Info Bar reconfirms the center anchor point based on the current character count.
![I1](https://github.com/goatcorp/Dalamud/assets/42252672/328aadc2-d3cc-4eda-bd01-2462609346c9)

![I2](https://github.com/goatcorp/Dalamud/assets/42252672/f41c48e7-0058-4f46-8929-b7a6874fa795)
![I2-1](https://github.com/goatcorp/Dalamud/assets/42252672/27df122b-9b18-410a-b1d3-126367e16969)

**Comment by nebel** [comment]
This issue was fixed in Dalamud a couple of weeks ago. Based on the language in the screenshots it appears you may be using a Dalamud fork? If so, the fork needs to update to get this fix.
