### ISSUE TITLE
GameConfig.cs Returns Null Reference During Plugin Load

### ISSUE THREAD

**Issue by Sebane1** [goatcorp/Dalamud#1529]
I'm providing this error log second hand as I've been unable to reproduce the issue on my own machine.
However several users appear to run into line 229 of GameConfig.cs throwing a null reference during plugin load of Artemis Roleplaying Kit.

I've tried everything on my part to ensure its not the plugin code itself inducing this error.

[dalamud error log.log](https://github.com/goatcorp/Dalamud/files/13326486/dalamud.error.log.log)

**Comment by KazWolfe** [comment]
We believe this may have been caused by some changes to service loading and management, which has been fixed in subsequent commits.

If you're still having this issue, please re-open this issue and upload a Verbose log with only the affected plugin. Thanks!

**Comment by Sebane1** [comment]
![image](https://github.com/goatcorp/Dalamud/assets/7157688/549a7426-a362-4190-8069-5301d954bad3)
Seems like somebody has managed to run into this bug again. I unfortunately wasn't able to get a verbose log out of the person.
Though, the line numbers affected appear to be shown clearly.

**Comment by Sebane1** [comment]
![image](https://github.com/goatcorp/Dalamud/assets/7157688/feed1ffe-7b21-4bc8-a315-f23fb29b5393)
Apparently this issue is still occurring for some people.
Unfortunately I wasn't able to get a verbose log out of the person.
I also don't appear to have the ability to re-open this issue.
