### ISSUE TITLE
Bug in loading dalamud

### ISSUE THREAD

**Issue by Elydraen** [goatcorp/Dalamud#1548]
I have a problem I can no longer launch the game from the Dalamud launcher, I try to run repairs, uninstall, nothing works, Thank you for your help
![bug](https://github.com/goatcorp/Dalamud/assets/94045746/0c193753-9e43-443f-aca6-e058ed8325d0)
![version](https://github.com/goatcorp/Dalamud/assets/94045746/cd77ecb6-dbad-4b4e-95a7-79d45f356e1f)

**Comment by Elydraen** [comment]
and if i launch without dalamud my game is ok

**Comment by KazWolfe** [comment]
Hi,

Thank you for opening an Issue! Given the age of this problem, I'm not sure there's anything we can do to help here. If you're still having issues, please consider joining [our Discord](https://discord.gg/holdshift) for realtime support. 

Thanks!
