### ISSUE TITLE
computer system freeze 

### ISSUE THREAD

**Issue by sinonx1** [goatcorp/Dalamud#1566]
haii i really need some help with this issue im having i will start from the beginning so it will be a longish story to try and cover as much detail:

a few  months ago i recently upgraded some hardware in my computer all was okay for a few weeks then i started to experience my system going into a heavy freeze/lag (effects both monitors) me and my partner tried alot of things to get to the issue but its a rollercoaster i even took my pc into a shop and they did 24 hour stress testing ect and cant find any issue with the hardware. every time we think we are getting closer to solving the issue we are thrown ,it doesn't seem to happen on any other game or the vanilla version of ffxiv i had even uninstall the game and the launcher and cleared out any mod/dalamud files and reinstall but still having the same issue. when the freeze/lag does happen i am able to use the win+ctrl+shift+B wich will reset my gpu and put things back to normal but it still happens after this issue can occur at any time and its really starting to get frustrating so i want your thoughts.

Q: can dalamud happen to be causing this issue and if so how?

Q: could i be having driver conflicts somewhere on my computer?

i am hoping there someone that's had the same issue as me and is able to help me fix this nightmare thank you for taking the time to read and i hope it makes sense 

sinon x

**Comment by KazWolfe** [comment]
Hi,

Thank you for your report. We can't really offer support for problems like this over GitHub. If you're still having issues, please join the [Dalamud Discord](https://discord.gg/holdshift) and bring your `dalamud.log` file from `%APPDATA%\XIVLauncher`.

Thanks!
