### ISSUE TITLE
GameConfig.cs Returns Null Reference During Plugin Load

### ISSUE THREAD

**Issue by Sebane1** [goatcorp/Dalamud#1672]
A revival of the following as I do not appear to be able to re-open the issue.
https://github.com/goatcorp/Dalamud/issues/1529

I was unable to get a full log from the person who reported this issue to me, but this should hopefully cover the key aspects of the error.
Was unable to get this to reproduce on my own machine.
![image](https://github.com/goatcorp/Dalamud/assets/7157688/555e23de-37b5-4fd8-9d6f-f4554ae2de3f)

**Comment by Soreepeong** [comment]
Yeah I can see this happening; it really is a race condition for plugins that load before GameConfig is fully initialized. On the access to plugin-scoped GameConfig it'll wait for the underlying service, but the wait is insufficiently done. I'll think about the solution later
