### ISSUE TITLE
Request for improvement of Japanese conversion input

### ISSUE THREAD

**Issue by torakiti2017** [goatcorp/Dalamud#1700]
・Use GoogleJapaneseIME

After converting Kanji in the plug-in window, the first character input is ignored.
Is it possible to prevent character input after kanji conversion operation from being ignored?

1. Enter "m" and "a" ("ま" will be displayed)
<img width="445" alt="1" src="https://github.com/goatcorp/Dalamud/assets/86459831/ae7404a2-6070-42b9-8d36-13f160e7f7b1">

2. Perform "space (or "conversion")".
<img width="441" alt="2" src="https://github.com/goatcorp/Dalamud/assets/86459831/4d487fb2-33b9-4535-ba27-40ccfaeb5f9d">

3. Enter "h" and "o"
4.★The input of "h" is ignored.
<img width="440" alt="3" src="https://github.com/goatcorp/Dalamud/assets/86459831/4aed3595-aa56-418e-8063-3e1dd37aab39">

The expected behavior in 4 is that when you input "h" and "o", "ほ" is displayed.
<img width="438" alt="4" src="https://github.com/goatcorp/Dalamud/assets/86459831/2197ac84-a360-449f-9288-ff64ce37186f">

I'm using translation. Sorry if it's hard to understand.

**Comment by torakiti2017** [comment]
It has been fixed and will be closed.
Thank you for responding.

**Comment by goaaats** [comment]
Apologies for not following up on this. If you notice any other weird things with Japanese IMEs, please continue opening issues on GitHub and we will try to fix it.

We don't have many Japanese users in our Discord so we don't usually discover these issues ourselves.
