### ISSUE TITLE
Getting error code trying to update a plugin in Dalamud

### ISSUE THREAD

**Issue by ThyArtt** [goatcorp/Dalamud#1727]
Hello i hope i can find here any help for my problem, i try to update since 3 days a plugin in dalamud and i always get the same error code and i don't know how to solve it he error code what i get is this one "the ssl connection could not be established, see inner expection" and under the error code is standing "the remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch" i hope someone can help me with this :/

**Comment by tommadness** [comment]
Have you ever used an antivirus by the name of Avira?

**Comment by ThyArtt** [comment]
no i just use microsoft defender but never was having a problem like this before

**Comment by tommadness** [comment]
Does this affect official Dalamud repository plugins (the ones with the blue check mark) or is this only affecting ones from a custom plugin repository? (the ones with a yellow ! icon)

**Comment by ThyArtt** [comment]
just the ones with a yellow icon like glamourer and mare and stuff

**Comment by tommadness** [comment]
If it is only affecting plugins that come from a custom plugin repository, we can not help you at all. Plugins from outside of Dalamud's official repository are entirely out of our hands and support.

**Comment by ThyArtt** [comment]
okay do you know maybe where i can ask for help then? :/

**Comment by tommadness** [comment]
As a rule we do not link to plugins outside our official repo. You will need to find their support Discord/github pages on your own.

**Comment by reiichi001** [comment]
Please ask on their respective discords/support sections. The custom repository plugins you've mentions all have buttons to join their discord in the plugin and on their github pages. You can find more information about a plugin from the globe icon in the plugin installer.
