### ISSUE TITLE
Dalamud crashing after Disabling and Enabling mods in Penumbra

### ISSUE THREAD

**Issue by Scranner1** [goatcorp/Dalamud#1746]
I recently used the XIV launcher's repair function to fix an issue with the game. It seemed to work at first, but now I'm experiencing crashes again after re-enabling and disabling mods.
[Dalamud Crash report.zip](https://github.com/goatcorp/Dalamud/files/14736080/Dalamud.Crash.report.zip)

**Comment by tommadness** [comment]
We are not responsible for and can not help you with any crashes that involve plugins outside Dalamud's official plugin repos. There are several warnings telling you this when you add the custom plugin repository.
