### ISSUE TITLE
AddonLifecycle PreDraw handler called after Unregistration

### ISSUE THREAD

**Issue by sourpuh** [goatcorp/Dalamud#1768]
After migrating NameplateDebuffs to use AddonLifecycle, I discovered that the PreDraw event handler (and possibly others) is called after it has been unregistered.

I added a log statement that demonstrates this behavior: https://github.com/sourpuh/NamePlateDebuffs/blob/67bd7101c0bdf4315b83242fb5f56fb45bef5b21/NamePlateDebuffs/AddonNamePlateHooks.cs#L42

Whenever I reload the plugin, this log is printed:
```
[INF] [LOCALPLUGIN] Unloading NamePlateDebuffs.dll
[INF] [LOCALPLUGIN] Finished unloading NamePlateDebuffs.dll
[INF] [LOCALPLUGIN] Loading NamePlateDebuffs.dll
[INF] [LOCALPLUGIN] Finished loading NamePlateDebuffs.dll
[ERR] [NamePlateDebuffs] AddonNamePlateDraw called after dispose
```

**Comment by MidoriKami** [comment]
AddonLifecycle uses a lazy unregister, registrations are removed on the following framework update, which occurs after the next set of per-frame events are sent to each window.

**Comment by sourpuh** [comment]
Thanks for the explanation. I understand the need to safely clean up handlers when plugins don't properly clean up after themselves, but this is surprising behavior for plugins that properly un-register handles.

What are the potential issues with performing un-registrations outside of the main thread? Could the behavior be changed to immediately un-register if called on the main thread?
