### ISSUE TITLE
IsValidCharacterName doesn't handle long names

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/Dalamud#1770]
There are people with longer names than 20 combined which means the IsValidCharacterName method may return false on some valid characters. Sounds like client has space up to 32 characters in most places. Could change the length. Maybe swap over to the cs check at the same time. In discord, goat recommended having a toggle for legacy name support.

https://github.com/kalilistic/Dalamud/blob/dbd59ebe91a2968960af90e142ac2c6f1c2028fa/Dalamud/Utility/SeStringExtensions.cs#L27
https://github.com/aers/FFXIVClientStructs/pull/381

![image](https://github.com/goatcorp/Dalamud/assets/35899782/4de72f46-e166-4bf3-b33b-b3a08e993d30)

**Comment by KazWolfe** [comment]
@kalilistic Has this been fixed with #1840?

**Comment by kalilistic** [comment]
> @kalilistic Has this been fixed with #1840?

Yes, all set. Legacy names are included in the validation by default and people can opt out with the optional parameter.
