### ISSUE TITLE
Crash when ReShade of specific versions is also injected to the game

### ISSUE THREAD

**Issue by liuxd17thu** [goatcorp/Dalamud#1836]
# How to produce:
1. Install custom ReShade build of this commit (https://github.com/crosire/reshade/commit/bb651288247fec7f2c1b9bdfc4a8b08a25ac9a62), or any other versions newer.
2. Launch FFXIV with Dalamud enabled
 The Dalamud icon (for dalamud setting / plugin manager) is missing, but it should have been on the left side of game title screen.
  **Meanwhile ANY keyboard input will make Dalamud crash immediately**
![Crash](https://github.com/goatcorp/Dalamud/assets/77222659/7423e400-9f16-4e63-ac7f-f8c7adb7a524)

The game integrity is good, and there are not any Dalamud plugins installed at all. I suppose there are some conflictions between ReShade's recent code changes and Dalamud's ImGui.

Crash tspack is here:
[crash-20240614131357.zip](https://github.com/user-attachments/files/15832040/crash-20240614131357.zip)

**Comment by goaaats** [comment]
Is this the exact commit that's causing the issue? Did you bisect reshade to arrive at it?

**Comment by liuxd17thu** [comment]
> Is this the exact commit that's causing the issue? Did you bisect reshade to arrive at it?

Yes, everything is fine with the previous commit (https://github.com/crosire/reshade/commit/30abcf65542b5a6de19a3ec3f3e5ae41b35b2290).

**Comment by Soreepeong** [comment]
Can't see any association with those reshade commits with Dalamud, but the crash log itself makes sense on its own. The above PR should fix this problem, at least for this stack trace in particular.
