### ISSUE TITLE
Can PlayerCharacter derive a type to distinguish local player from other players?

### ISSUE THREAD

**Issue by sbago** [goatcorp/Dalamud#1847]
Can PlayerCharacter derive a type to distinguish local player from other players, making it easier for developers to write extension method code?

**Comment by KazWolfe** [comment]
What's your use case? There's nothing special about the local player itself really, so whatever works on any remote player _should_ also work on your `LocalPlayer`.

**Comment by sbago** [comment]
> What's your use case? There's nothing special about the local player itself really, so whatever works on any remote player _should_ also work on your `LocalPlayer`.
You're right. I just want to change my code style to that accessing game information must start with a GameObject object. For example, if I want to access backpack items, ideally I would derive a PlayerCharacter type, but since the constructor of PlayerCharacter is internal, I cannot inherit it. I'll try the wrapper class for my local character and see if the source generator can help me. Anyway, thank you very much.
