### ISSUE TITLE
DLSS with Dalamud in Linux

### ISSUE THREAD

**Issue by Kitsune-Kuro** [goatcorp/Dalamud#1859]
Hello,

I have installed Dalamud on Ubuntu via Flatpak.
However, I cannot enable DLSS from Nvidia in the system settings.
When I start FFXIV on Steam without Dalamud, I can select it.

DLSS is supported in FFXIV since dawntrail/v7.0.

I have installed version 1.1.0 of dev.goats.xivlauncher.
Nvidia driver version: nvidia-driver-535

OS: Ubuntu 22.04.4 LTS x86_64 
Kernel: 6.5.0-41-generic 
Shell: bash 5.1.16 
Resolution: 3840x2160 
DE: GNOME 42.9 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: NVIDIA GeForce RTX 3070 Ti 
Memory: 5377MiB / 23962MiB 

Thank you for your assistance.

**Comment by tommadness** [comment]
You're looking for https://github.com/goatcorp/XIVLauncher.Core

Dalamud is the plugin system which **has not been updated for Dawntrail yet** and as such can have 0 impact on your ability to use DLSS.

**Comment by Kitsune-Kuro** [comment]
I would like to thank you for your clarification and help regarding the issue.
I didn't know about https://github.com/goatcorp/XIVLauncher.Core.

Thank you very much!
