### ISSUE TITLE
Bundled Lumina throws NullReferenceException on Adventure.Name

### ISSUE THREAD

**Issue by anna-is-cute** [goatcorp/Dalamud#1880]
Try to access the `Name` property on any row in the `Adventure` sheet and it will throw a NullReferenceException.

**Comment by NotNite** [comment]
I can't reproduce this:

```cs
Services.PluginLog.Info(
    Services.DataManager.GetExcelSheet<Adventure>()!
        .GetRow(2162688)!
        .Name.ToString()
);
```

Is this with GeneratedSheets or GeneratedSheets2? Do you know what row this happens on?

**Comment by anna-is-cute** [comment]
It may be then that a NuGet dependency is loading in an old version of Lumina, which is taking precedence over the one in the lib path, since I can't even resolve GeneratedSheets2, not that I know the difference.

**Comment by anna-is-cute** [comment]
Ah, yes, the weather NuGet package does indeed take precedence. Ignore me, then.

**Comment by NotNite** [comment]
> since I can't even resolve GeneratedSheets2, not that I know the difference.

JSYK: GeneratedSheets2 uses [EXDSchema](https://github.com/xivdev/EXDSchema) instead of SaintCoinach for sheet data, but it has some issues with Dawntrail right now.
