### ISSUE TITLE
WorldToScreen returns false when it shouldn't

### ISSUE THREAD

**Issue by anna-is-cute** [goatcorp/Dalamud#1881]
Noticed this in Peeping Tom, but you can reproduce it in the /xldata object table viewer. None of the labels will draw because it returns false. Whether this is a problem with the Location property or a problem with WorldToScreen itself, I do not know.

**Comment by wolfcomp** [comment]
Check what Umbra is doing since i know it uses a similar method. It was something that we noticed with 7.0 being a bit broken.

**Comment by pohky** [comment]
oh didn't see this or i would've mentioned it in the pr
#1885 should solve this

**Comment by goaaats** [comment]
@anna-is-cute Please close if this works for you now!

**Comment by anna-is-cute** [comment]
Sorry, I was asleep. Looks fixed to me!
