### ISSUE TITLE
XivApi item search can't find items with '+' in the name

### ISSUE THREAD

**Issue by ff-meli** [goatcorp/Dalamud#19]
Example item "Elemental Blade +2" (ID 24068)

This is annoying and appears to be a limitation of xivapi's actual query handling, as even manually searching for anything with a '+', encoded or not, will fail.

Their docs mention querystring/GET search is deprecated and they now use elasticsearch via json body data.  I was able to get a query with a '+' working in their search playground using that, but I didn't spend enough time to figure out what is necessary to make that work at least on parity with the existing search.

Example post body for searching for that particular item (git formatting hates me): ```{
  "indexes": "item",
  "columns": "ID,Name,Icon",
  "body": {
    "query": {
      "wildcard": {
        "NameCombined_en": "*blade +2*"
      }
    },
    "from": 0,
    "size": 1
  }
}```

**Comment by ff-meli** [comment]
I created a potential implementation of this, but I had some open questions so I wasn't sure it was ready for a PR.  A diff is here https://github.com/goaaats/Dalamud/compare/master...ff-meli:xivapi_search_post

Mostly I'm not sure what the intended behavior is with respect to non-english clients.  It looks like the old behavior required users to search in english always, and it returned the english name always.  The actual item link that is generated would obviously be localized, but I'm not sure if the name would appear wrong in the chat box, or if the game actually corrects that etc.

This implementation keeps the "english only" behavior, but it does look like we could support searching and displaying in the client language with only a little messiness (a subclass of DefaultContractResolver somewhere, and a way to get a language suffix string from a client language).  Not really sure what is intended behavior though.

**Comment by goaaats** [comment]
/xlitem is retired now, the item search plugin can do a better job
