### ISSUE TITLE
The Overlays seems to have an occasional flicker

### ISSUE THREAD

**Issue by StellarJay77** [goatcorp/Dalamud#191]
All the overlays seem to have an occasional flicker like they are briefly losing focus and then regaining focus again. It is especially noticeable in the "Teleporter" plugin on the AetherGate overlay. When adding new teleport buttons if it flickers the new button edit window closes and has to be reopened again to continue adding the information in for it. This only started to occur on the last couple updates to the Launcher and/or the plugin.

**Comment by daemitus** [comment]
please reopen if this is still an issue.
