### ISSUE TITLE
Game crashes when entering chara make/aesthetician

### ISSUE THREAD

**Issue by seathasky** [goatcorp/Dalamud#192]
**Describe the bug here:**
Game crashes when I typed /xlplugins.
It opens the window briefly and the FF14 crashes 4 seconds later.

**Steps to reproduce the bug:**
typing /xlplugins.
Plugins still work outside of typing to get plugin list. I tested everything that i have installed.

**Expected behavior**
typing /xlplugins should populate a list of plugins and their config.

**Other information (*please* complete the following information):**
  Operating System: Windows 10 latest update
  XIVLauncher version: 5.1.1.0
  Launching as admin?: no
  Using Steam?: no
  Addons/Plugins enabled:
mouseover, soundsetter, xivcombo, and marketplace.

Gshade also installed. But i've tested with and without and still get the crashes. I've also tested in a base game install with no addons, plugins etc, just fresh install and I do not get crashes. Something with XIV Launcher is crashing the game.

**Comment by robotbrain** [comment]
[whee.zip](https://github.com/goatcorp/Dalamud/files/5462420/whee.zip)
as per discussion in discord after some testing, issue is consistent with goodmemory and fpsplugin installed but not with either individually, and happened once but not reproducible with fpsplugin and richpresence

**Comment by goaaats** [comment]
This should not be happening anymore with the plugins currently released.
