### ISSUE TITLE
Should the GameObjectId of the GameObject class be assigned in the constructor?

### ISSUE THREAD

**Issue by sbago** [goatcorp/Dalamud#2051]
Should the GameObjectId of the GameObject class be assigned in the constructor? Note that it has this code segment

bool IEquatable<IGameObject>.Equals(IGameObject other) => this. GameObjectId == other?.GameObjectId; 

Assuming that I maintain references to instances of GameObject for a long time, there may be potential risks when calling this code.
Many linq functions call this function

**Comment by MidoriKami** [comment]
>> Assuming that I maintain references to instances of GameObject for a long time, there may be potential risks when calling this code.

You should not be holding references to a game object for more than the frame that you acquired the reference on.
