### ISSUE TITLE
`Character.StatusFlags` throw `Unhandled native exception occured at 0`

### ISSUE THREAD

**Issue by Pilzinsel64** [goatcorp/Dalamud#2128]
When accessing the getter of `Character.StatusFlags` while you exit GPose Dalamud throws an unhandled native exception. This happens e.g. for Player Tags as the plugin tries to get the player's status flags as soon as the current activity context has been changed.

Guesses from Discord: null or invalid pointer

![](https://media.discordapp.net/attachments/653504487352303619/1311607685606805555/image.png?ex=67497958&is=674827d8&hm=d499cbc1e26b8b9e3bc620cfcf7777ff3a2730624c695db6d98fe3de754b3d84&=&format=webp&quality=lossless)

If you need more infos, please just tell me.

**Comment by nebel** [comment]
Should be fixed by #2129.
