### ISSUE TITLE
BGM set to None when opening About screen in an instance

### ISSUE THREAD

**Issue by Secrean** [goatcorp/Dalamud#2130]
Steps to reproduce:
1. Go into an instance
2. Open Dalamud Settings
3. Click on About
4. go out of About

Expected result: BGM goes back to playing the instance's current song
Actual result: No BGM playing.

Happend to me in FRU, getting to a new phase fixes the issue as new BGM starts playing.
I've also tested it in Emanation.

**Comment by nathanctech** [comment]
Interesting bug. Apparently, this happens on *any* raid or trial (that I've tested, from any expansion) and any dungeon that is 2.1 or later. The swap back does work on 2.0 dungeons (Sastasha through Amdapor Keep) but breaks after that. Didn't test alliance raids, but I'd expect similar behavior. Dalamud internally sets the song to "9999" on close which I think makes the game fall back to the previous track, but in those cases it doesn't and just gets set to 1 (None).
