### ISSUE TITLE
2 bars superimposed in the numbers

### ISSUE THREAD

**Issue by J1MS01** [goatcorp/Dalamud#2157]
Hello guys, i don't understand why I have these 2 bars that slip between the numbers. It looks like it's replacing the spaces. 
![dalamud bar](https://github.com/user-attachments/assets/13850039-69a2-4b87-88ce-3a51c7ce2b75)

I've tried changing the font (lato) and that corrects the bug for Dalamud, but despite that the bug also affects the plugins I install...
![damalud lato font](https://github.com/user-attachments/assets/2fb40f77-02cf-4438-88d7-e97c43a5baaf)

Example with the Price Insight plugin :
![Price Insight bar](https://github.com/user-attachments/assets/1b95b318-e60d-4262-bc7c-96cf87823262)

If anyone knows how to fix this, that would be great. 

Thanks in advance.

**Comment by wolfcomp** [comment]
This is related to your computer locale. Seeing its french it's the french number split causing it which can be changed: `Control panel -> Change date, time and number formats -> Additional settings -> Digit grouping symbol`

**Comment by goaaats** [comment]
We should treat this as a bug and either change the formatting specifier in the .NET locale for Dalamud or make sure that the font has that glyph, though considering the game font is missing it too, we should probably do the former.

**Comment by J1MS01** [comment]
Hi guys,
Yes, I'm French. Sorry I forgot to mention that 😅
Thanks @wolfcomp, I followed what you told me and changed the symbol which was " ", so just an empty space to "." and now it works!
![its work](https://github.com/user-attachments/assets/16013aa0-1597-4fe4-9092-653c880e2592)

Sorry for the inconvenience...

I wish you a very happy holiday season 🥳
