### ISSUE TITLE
The command /xltoggleplugin does not exist.

### ISSUE THREAD

**Issue by StarkITA** [goatcorp/Dalamud#2159]
Hello,

I've been trying to use /xltoggleplugin, but unfortunately it does not work at all. Is it something I should enable somewhere, is it intended and not completely implemented?

When I use it it says: "[0:00]The command /xltoggleplugin does not exist."

Thanks :)

**Comment by Nareese** [comment]
The individual plugin enable/disable/toggle commands are currently only available on the beta testing (stg) release of Dalamud.  They will be generally available with the next full release.

**Comment by StarkITA** [comment]
Thanks! ♥
