### ISSUE TITLE
XivApi item search sometimes returns incorrect results even for exact item names

### ISSUE THREAD

**Issue by ff-meli** [goatcorp/Dalamud#22]
Related to #19 

Sample items with wrong results include "Revolver" and "Deathbringer" (and I believe most job gear that has a normal variant plus something like an antiquated variant etc).

We should eventually switch to the elastic search version as mentioned in #19 , but a more immediate fix for this might be to add a parameter to the command, or an additional command, or check if the item name is a quoted string... just some way to flag that the user wants an 'exact' query.  If it is, we can append to the existing xivapi query "&string_algo=match", which will then return the correct result at the expense of the user having to type the full item name.

Note the algo change won't address the problem(s) in #19 so we'll still need to switch to elastic search at some point to handle everything.

**Comment by ff-meli** [comment]
_Eventually_ item search might be a nice thing to tie into the UI, once that is integrated and working decently.  It still might be best to have it be optional for people who don't want window spam, but adding the option for users to see the full list of results and pick one would be nice, especially in the case that they aren't doing an exact search.

**Comment by goaaats** [comment]
We switched to Lumina for this and added UI to search items, so this should no longer apply.
