### ISSUE TITLE
Cannot get the launcher to launch the game

### ISSUE THREAD

**Issue by Kadengt** [goatcorp/Dalamud#248]
Good Morning!, I just found out about the xivlauncher and I was trying it out. Everything installed just fine and when I tried to use it, it gave me this error : 

"Failed to inject the XIVLauncher in-game addon. Please try restarting your game and your PC. If this keeps happening, please report this error."

I restarted the game, and PC, and it did not fix it. I tried to run as administrator as well, did not fix. I googled the issue but I did not find anything really about it, maybe I didn't word it correctly. I found an old post about a Discord issue, but that seems to of been fixed back in Dec. 2019. I have discord installed but it is not running at all. I am currently on Windows 10 also. If you need other information I will be happy to try and get it for you. 

Thank you

**Comment by Caraxi** [comment]
Please post your log files (below) so that we can get a better idea of what might be happening.
`%appdata%\XIVLauncher\output.log`
and 
`%appdata%\XIVLauncher\addon\Hooks\dalamud.txt`

(These files may have some minor idenitifying information such as your windows and ffxiv username so you may wish to edit those out if that worries you.)

**Comment by Kadengt** [comment]
[output.log](https://github.com/goatcorp/Dalamud/files/5837479/output.log)

I've tried to look for the 2nd one, but I do not have the dalamud.txt file.

**Comment by Caraxi** [comment]
Try deleting the entire `addon` folder and then check if your antivirus is triggering a false positive on anything.

**Comment by Kadengt** [comment]
I deleted the entire folder and disabled Windows defender firewall. It launched the game this time, but it gave me the same error. I tried the command /xlhelp in game and it did nothing.

**Comment by daemitus** [comment]
If you still have this issue, please reopen a new ticket.
