### ISSUE TITLE
ImGui is really old

### ISSUE THREAD

**Issue by ascclemens** [goatcorp/Dalamud#251]
Periodically I run across issues with ImGui that are already fixed in upstream. I know this affects other people, and generally we can find workarounds, but it would be nice to just... have the fixes.

Dalamud uses a version of ImGui released on 31 July 2019. It would be nice to update it.

**Comment by goaaats** [comment]
I'll have to look into merging ImGui.NET upstream - shouldn't be too difficult, but if it's causing any unintended behavior with ImGuiScene that I can't easily fix I'll probably hold off on it for now.

**Comment by goaaats** [comment]
I'm very happy to announce that perchbird has been appointed Chief ImGui Officer and has a workflow for doing this more regularly now. Thanks!
