### ISSUE TITLE
ImGui component library and new windowing infrastructure for Dalamud core

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#287]

**Comment by kalilistic** [comment]
Maybe a stretch goal but could consider a window like the imgui demo to see these any comments in action.

**Comment by kalilistic** [comment]
How do you want to handle components that have returns? The only interface method at the moment is void draw(). Was playing around with a custom button and got it working with callbacks. Not sure if there's a better way though...

`
var isClicked = false;
var iconButton = new IconButtonComponent(FontAwesomeIcon.Carrot, result => isClicked = result);
iconButton.Draw();
if (isClicked) PluginLog.Log("Clicked!");
`
