### ISSUE TITLE
Correct names of Addon/Atk classes

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#290]
Dalamud uses some wrong naming for classes related to game UI because I didn't know any better. Would be nice to fix those.

We can use this issue to collect them.

**Comment by daemitus** [comment]
Technically Actor is GameObject, and a ton of shit is just BattleChara.

**Comment by daemitus** [comment]
Got most, addon is pending in #477

**Comment by daemitus** [comment]
done afaik
