### ISSUE TITLE
Remove focus from text input fields on mouse click in game

### ISSUE THREAD

**Issue by Eternita-S** [goatcorp/Dalamud#343]
Currently if you have imgui text input field focused, it will stay focused after mouse click occurs inside game, but outside of imgui windows (and will keep intercepting keyboard input). If a click occurs inside imgui window then focus is taken away from input field. Is it possible to automatically unfocus text inputs even after click happening outside of imgui windows?

**Comment by goaaats** [comment]
I fixed this recently. Requires focus management to be enabled in the Dalamud settings.
