### ISSUE TITLE
XIV Combo: Expand Skill combos

### ISSUE THREAD

**Issue by pochte** [goatcorp/Dalamud#353]
Sch: 
Lustrate Turns into Aetherflow if no stacks available, 
Indomitability turns into Aetherflow if no stacks available.
Doesn't happen under effect of Recitation
Summon Seraph turns into Consolation if Seraph is out 

Whm:
Afflatus Misery automatically targets your target's target since you're using targetting the tank.

Rdm: 
Turn veraero/verthunder into verstone/verfire if it's procced.

Blm:
Turn Thunder 3 into Thunder 4 if procced

Dnc:
Turns Reverse Cascade into Cascade version if not procced
Turns Fountainfall into Fountain if not procced

General: 
Option to make the icon that displays with icon lock the end of the combo icon.

**Comment by Caraxi** [comment]
Issues related to specific plugins should be directed to their own repo, not to dalamud itself.
https://github.com/attickdoor/XIVComboPlugin/
