### ISSUE TITLE
Add the option to limit the amount of lines in the in-game logging window

### ISSUE THREAD

**Issue by WesselKuipers** [goatcorp/Dalamud#360]
When messing with the logging in my plugin I ended up having so many log entries that it would lag a lot in-game trying to render/keep track of every line that was logged since the last time it was cleared.

To help with this I think having a way to limit the amount of entries would help reduce the lag, probably in the form of an optional and configurable amount of lines. 

I wouldn't mind adding this myself.

**Comment by Aireil** [comment]
Pretty sure that is no longer lagging as it used to.
