### ISSUE TITLE
/xldreload disables all plugins instead of reloading

### ISSUE THREAD

**Issue by cmckelvy42** [goatcorp/Dalamud#382]
Using /xldreload simply disables every plugin installed plugin until the game is restarted instead of actually reloading anything

**Comment by daemitus** [comment]
Confirmed: current code only reloads synchronous plugins (priority > 0).

**Comment by goaaats** [comment]
That's not the point of the issue though. Actual "reloading" is impossible with .NET Framework, without LPL workarounds.

.NET 5 Dalamud will have this.

**Comment by daemitus** [comment]
I took reloading not as in reloading from disk but re-instantiating the plugin implementation.

**Comment by daemitus** [comment]
All plugins re-read from disk on "reload" now.
