### ISSUE TITLE
Memory permissions are causing crashes (net5)

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#385]
During testing of AllowDebug and why it was causing crashes, it was discovered that it seems as if memory permissions are not handled automatically anymore.

AllowDebug uses Marshal.Copy to nop over the IsDebuggerPresent call. After replacing that was Reloaded.Memory's ExternalMemory.SafeWriteRaw which handles permissions, the game and plugin were stable again.

Either EasyHook or the .NET framework itself handled permissions for us. 

So how do we fix this?

Should the plugin author be cognizant of it and not screw up?
Should Dalamud just set permissions on everything as writable?

**Comment by goaaats** [comment]
Do we have a .NET Core change to cross-ref this with? I skimmed the documentation and couldn't find anything specific.

Maybe @Minoost or @NotAdam would know?

**Comment by daemitus** [comment]
I've got nothing to go on other than it worked before, now it doesnt, and doing VirtualProtect fixes it.

**Comment by NotAdam** [comment]
there isn't actually any guarantee by the .net framework that protection is checked when calling marshal.copy, the fact that it ever worked is sheer dumb luck because it's certainly not a supported use case

in .net core they basically just implement memmove and assume that the destination is writable, which realistically is the intended behavior

**Comment by daemitus** [comment]
Think their memmove implementation trying to access an unallocated page will still cause an access violation? Thinking of the actor table hack.

**Comment by NotAdam** [comment]
it will because it would touch unallocated/protected memory in the worst case and cause an access violation. my PR has a fix for that actor table hack fwiw

**Comment by daemitus** [comment]
looks resolved.
