### ISSUE TITLE
Suggestion to add categories to plugins

### ISSUE THREAD

**Issue by insarius** [goatcorp/Dalamud#386]
With the ever growing list of plugions, can we have categories for certain types of plugins?

For example a tab for battle centric plugins like XivCombo and RemindMe.

That way I won't have to scroll through a list in search of something, or when something new gets added it's more easily spotted.

**Comment by daemitus** [comment]
We currently support tags as an item in each plugin manifest, however it's up to the author to add them. It'd be easy enough to add categories as a sort view, however "new" would be something entirely different.

**Comment by insarius** [comment]
> 
> 
> We currently support tags as an item in each plugin manifest, however it's up to the author to add them. It'd be easy enough to add categories as a sort view, however "new" would be something entirely different.

Not necessarily a tab for new plugins, what I meant was if the list showing "Battle"-tagged plugins suddenly has an extra entry it'll be easier to spot. :)

I think enabling a tab view to separate based on tabs is wonderful.

**Comment by MaikoTan** [comment]
I think I'd prefer a "Filter" dropdown menu rather than tabs, when you select "Battle" category, then only plugins tagged "Battle" would be shown.

**Comment by insarius** [comment]
> 
> 
> I think I'd prefer a "Filter" dropdown menu rather than tabs, when you select "Battle" category, then only plugins tagged "Battle" would be shown.

That works too! <3

**Comment by daemitus** [comment]
tags == categories
