### ISSUE TITLE
Crash at plugin window from abberant 3rd party repo

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#397]
The following repo list causes a CTD from the plugin installer window. why? who knows. lets investigate!

SHH SECERET DONT LOOK AT THESE.
```
"ThirdRepoList": [
    {
      "Url": "https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/master/pluginmaster.json",
      "IsEnabled": true
    },
    {
      "Url": "https://git.sr.ht/~jkcclemens/plugin_repo/blob/master/pluginmaster.json",
      "IsEnabled": true
    },
    {
      "Url": "https://raw.githubusercontent.com/maributt/xivplugins/main/repo.json",
      "IsEnabled": true
    }
  ],
```

**Comment by PrincessRTFM** [comment]
Second URL is defunct, she moved it to https://plugins.annaclemens.io/unofficial instead. The URL you're using is returning a 404 with HTML content.

**Comment by reiichi001** [comment]
I think Daemitus was aware that the URL was a 404, but the issue is more "why does a 404 crash the plugin window" when it should instead only be showing the "one or more of your third party repos failed to load" text.

**Comment by goaaats** [comment]
This was on net5 so I added the respective label.

**Comment by daemitus** [comment]
Cannot replicate :(

![Screenshot 2021-07-13 113735](https://user-images.githubusercontent.com/706948/125482243-62589c88-cb46-456c-944c-7d6a7431bc72.png)

Can I get a few more confirmations of this working?

**Comment by PrincessRTFM** [comment]
Has XL updated? (Also, doesn't that mean the issue's fixed, since it's no longer a CTD on failure?)

**Comment by daemitus** [comment]
That particular bit of code hasn't, not since goat pushed net5 to testing.

**Comment by daemitus** [comment]
No complaints lately, could not replicate. Closing until it crops back up.
