### ISSUE TITLE
Plugin cleanup / installation general behavior discussion

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#404]
So currently cleanup blows everything away if its invalid, disabled, whatever. Not gonna load, not staying around.

Should the original functionality of a lesser API level only inflict disabled or should it delete?

When a "installedPlugins" plugin is disabled, the property is set and scheduled for cleanup next boot. However if a re-installation happens before then, it is re-downloaded regardless of files on disk currently. Should Dalamud attempt to re-load from disk?

The .disabled and .testing file functionality was moved into the pluginname.json manifest file. Is there a better way to implement disabled plugins than what we're currently doing in general?

**Comment by Aireil** [comment]
In my opinion, game version / lower API should not be deleted, nor disabled. When a new version is up, Dalamud should update it and enable the plugin again.
So I would say keep the old behavior, just ignore until there's an update.

**Comment by daemitus** [comment]
Ok. So ultimately: 
- API OR gameversion mismatch: ignore, add to a special list for update eligible. Comment out checks in cleanup method.
- On install, check for existing files to save a download.

**Comment by kalilistic** [comment]
Not a direct answer but a related feature was discussed awhile ago and could impact this (maybe?). The idea was showing plugins that are one API level behind as greyed out rather than hidden all together. This might help stem the questions like "where is my owo plugin" after patch days.

**Comment by goaaats** [comment]
This would be ideal and would allow for the installer to update those plugins whenever they get updated.
