### ISSUE TITLE
Outdated plugins can never be updated

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#409]
PluginManager::DetectAvailablePluginUpdates() only checks its own availablePlugins for updates - this never has any plugins with a lower API level than the current.

**Comment by daemitus** [comment]
It has the current API level, or all if this.dalamud.Configuration.LoadAllApiLevels is set.

Should it update to a level if wouldn't be loaded without that flag?

**Comment by goaaats** [comment]
Well, the problem currently is that as such, it can never detect any updates from the previous API level.

I'll try to just aggregate all repos with ApiLevel <= PluginManager.DalamudApiLevel in DetectAvailablePluginUpdates() again.

**Comment by daemitus** [comment]
Just hack up PluginManager.IsManifestEligible, it's only used to filter the availablePlugins directly from the repos.

**Comment by daemitus** [comment]
bleh. then old plugins will be shown though. Yeah, you're right
