### ISSUE TITLE
enable multi-monitor windows for single monitors

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#442]
Dude in discord has an ultrawide 5000x monitor and software to emulate multiple monitors. Should probably allow for multi-monitor in this situation

**Comment by lmcintyre** [comment]
I cannot see a downside to this situation. As long as we keep "multi-monitor" an opt-in feature.

**Comment by Dormanil** [comment]
Doesn't even have to be the extreme of a giant ultra-wide. Maybe people just have their game in Windowed Mode for whatever reason, and should thus be reasonably able to drag imgui windows out of the FFXIV window.
