### ISSUE TITLE
Images in the Plugin Installer

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#447]
Plugins should be able to specify an array of screenshots in the plugin manifest.

When opening a plugin's header for the first time, the images will be fetched asynchronously and shown once downloaded.

Ideally these images will be in a fixed resolution because I don't want to make good UI.

**Comment by daemitus** [comment]
Love it. Should the devs offer smaller preview image as well as the full resolution?

I think the images should only show before the plugin is installed maybe?

**Comment by reiichi001** [comment]
This would be nice. Even better if we could deprecate the manual work for the plugin gallery and use those screenshots (and maybe some curated explanations) to generate basic readme content

**Comment by kalilistic** [comment]
> 
> 
> Love it. Should the devs offer smaller preview image as well as the full resolution?
> 
> I think the images should only show before the plugin is installed maybe?

I think images could still be useful after installation. For example, I install something and I'm not quite understanding how to use it...I might find some hints in the screen shots.

**Comment by goaaats** [comment]
> Love it. Should the devs offer smaller preview image as well as the full resolution?

No, but if we write code for this we might as well offer the option to have a plugin icon.

> I think the images should only show before the plugin is installed maybe?

Yes.

**Comment by goaaats** [comment]
> 
> 
> 
> > 
> > 
> > Love it. Should the devs offer smaller preview image as well as the full resolution?
> > 
> > I think the images should only show before the plugin is installed maybe?
> 
> I think images could still be useful after installation. For example, I install something and I'm not quite understanding how to use it...I might find some hints in the screen shots.

I have changed my opinion, we should

**Comment by daemitus** [comment]
icon.png/image1-5.png implemented.
