### ISSUE TITLE
ChangeLog in Plugin Installer

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/Dalamud#462]
Add new field to plugin installer / manifest to allow devs to keep a change log. This would allow users to see what has changed without checking discord or github. Maybe even printed to chat later with the plugin update message. Dae mentioned this could be an array of versions/strings.

**Comment by goaaats** [comment]
Plugins that update and have the Changelog property set on their manifest will now show a green changelog in the installed plugins tab.
