### ISSUE TITLE
Minor issues with Windows 11

### ISSUE THREAD

**Issue by BSoD38** [goatcorp/Dalamud#483]
Okay, so the issues might not be directly Dalamud-related, and caused by incompatibilities by using a beta version of Windows 11, but I thought it could be a good idea to have the issue written somewhere.

I have noticed two small issues with Dalamud since using Windows 11 (beta channel) :

- When an overlay appears while in multi-screen mode (outside the game window), or the overlay window is moved outside of the game window (and was originally inside the game window), the game will freeze for about a second systematically. The easiest way to reproduce this is to open any overlay window, such as Dalamud settings or Dalamud plugins list, move it outside the game's window, and toggle the UI (using Scroll Lock key by default). Each time the UI should reappear, the game will freeze for a second because one of the overlay windows is outside the game window.
- Certain plugins that separate their number thousands with a space (the only example I could find is the tax calculator tweak in Simple Tweaks and PMB) has the separator replaced with another character. In PMB it's replaced with an unknown character (or a question mark), and in Simple Tweaks it's replaced with a strange thick "=" character. I'll join a couple of screenshots to show the issue. This might be a Windows 11 issue not really fixable by developers, but by Microsoft themselves, as I've had the same issue on the game Warframe, where damage numbers separators were replaced with a "*".

![PMB](https://i.imgur.com/wFTi0KQ.png)
![Simple Tweaks](https://i.imgur.com/JcW7ioV.png)

Tested with build 22000.132.

**Comment by goaaats** [comment]
Is there a non-insider build of Windows 11 yet? I probably won't be looking into this until then, and I probably won't be using it on my workstation for quite a while to come.

Thanks for reporting anyhow, very helpful.

**Comment by BSoD38** [comment]
No problem.

Windows 11 is stated to release in late 2021, so there's only dev and release insider builds for now.

**Comment by namidairo** [comment]
Are you still experiencing this @BSoD38 ?

Saw this and decided to take a look, can't seem to replicate either behaviour on 22000.194, currently in the "Release Preview" channel.

![image](https://user-images.githubusercontent.com/1764089/135393774-5a0e1bda-edeb-4588-b425-caa7d8c72b02.png)

**Comment by BSoD38** [comment]
I played on my Windows 11 machine yesterday, and I think I still had the issue. I'll wait for the release of the OS next week to reinstall it clean and test again.

**Comment by BSoD38** [comment]
Hello again, Windows 11 has just released, and I reinstalled the release ISO on my system.

I can confirm that I still have the issue on a clean normal install.

This may be useful to note that my system is in French. The locale settings might be breaking something.

I also tried the latest dev insider build before reinstalling and I still had the issue.

**Comment by goaaats** [comment]
Is this not because of number formatting?

@BSoD38 could you take a screenshot of this page in Control Panel?
![image](https://user-images.githubusercontent.com/16760685/136261594-d9503def-d7f0-4872-ba9d-5bb0e1d21721.png)

**Comment by goaaats** [comment]
Can you post the character that is used as a space?

**Comment by BSoD38** [comment]
Sure.

```
 
```

**Comment by goaaats** [comment]
Seems this is "Narrow no-break space"
https://www.fileformat.info/info/unicode/char/202f/index.htm

**Comment by goaaats** [comment]
Since this isn't directly related to Dalamud, I'll close this issue. If the problem with the space still happens, please create an issue in Simple Tweaks.
