### ISSUE TITLE
I can't open dalamud windows when I start FFXIV

### ISSUE THREAD

**Issue by Helyan47** [goatcorp/Dalamud#493]
Hello,
I'm having an issue when I try to open Dalamud Settings or Dalamud Plugins windows via Esc or chat commands. Any of the windows pops up but when I start the game in chat appears the message Dalamud vD5.2.7.0... and the command /xlhelp works correctly.
I read the logs and the unique message I don't understand is:
TROUBLESHOOTING:eyJMb2FkZWRQbHVnaW5zIjpbXSwiRGFsYW11ZFZlcnNpb24iOiI1LjIuNy4wIiwiR2FtZVZlcnNpb24iOiIyMDIxLjA3LjE1LjAwMDAuMDAwMCIsIkxhbmd1YWdlIjoiRW5nbGlzaCIsIkRvRGFsYW11ZFRlc3QiOmZhbHNlLCJEb1BsdWdpblRlc3QiOmZhbHNlLCJJbnRlcmZhY2VMb2FkZWQiOnRydWUsIlRoaXJkUmVwbyI6W119
But after that it says:
Dalamud is ready.
Starting plugin update... dry:true
Plugin update OK.
I have XIVLauncher with DirectX11 option checked.

**Comment by daemitus** [comment]
Can you please bring this to the xivlauncher-issues channel at https://discord.gg/kHDc67uW. We'll be able to more actively help troubleshoot.
