### ISSUE TITLE
TargetObject and TargetObjectId always null

### ISSUE THREAD

**Issue by jdsmith2816** [goatcorp/Dalamud#501]
When I'm attacking an enemy in V4 that enemy's TargetObject and TargetObjectId are always null rather than pointing back to my character.  This works properly in v3.

Potentially relevant troubleshooting from discord:
![image](https://user-images.githubusercontent.com/556678/130981695-b7efd7c3-0223-4f78-b4d7-ce8935081b29.png)

**Comment by daemitus** [comment]
fixed
