### ISSUE TITLE
Plugin Stats window crash

### ISSUE THREAD

**Issue by UnknownX7** [goatcorp/Dalamud#532]
![image](https://user-images.githubusercontent.com/12263784/132092468-1b0be0d1-1a82-4ba9-ad62-38cabf200dac.png)
![image](https://user-images.githubusercontent.com/12263784/132092876-aa1fb55a-714d-4540-b12d-799a6492a2d0.png)

Seems to occur whenever I have any combination of more than 10 plugins, occurs about 1-2 minutes after opening the window regardless of if it was closed or not.

**Comment by goaaats** [comment]
Pretty sure this is good now
