### ISSUE TITLE
Need a command to revert to default BGM

### ISSUE THREAD

**Issue by Metaknight3** [goatcorp/Dalamud#56]
I am very unsure if this behavior is intentional but using the /xlbgmset command will force the music to never change between locations, instances, or areas beyond the set song. Additionally this change will only be turned when when re-logging, or closing and relaunching the client entirely. There appears to be neither an option for turning off this change, nor an option to find out what bgm id corresponds to what. Parsing through at least 708 numbers for songs isn't exactly desirable when I wish to reset the bgm itself.

**Comment by goaaats** [comment]
This is worked around by Aida in #43, I may merge that soon but I should really find the correct way to reset it.

**Comment by daemitus** [comment]
@goaaats should /xlbdmset 0 shortcut to 9999 to imeplement this functionality?

**Comment by Aireil** [comment]
/xlbgmset still clinging to life, but giving it no argument does reset the bgm, so that is indeed fixed! :)
