### ISSUE TITLE
Market board data uploads only include first history (and listing?) packet

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/Dalamud#588]
Market board responses from the server include multiple history packets, with up to 10 entries per packet. Dalamud only seems to send the data in the first packet. Capturing all packets can either be done with the MarketBoundCount packet or a debounce, like Teamcraft does. I reviewed Universalis's code, and this doesn't seem to be an issue on my end.

For reference, here's data received from a Teamcraft upload, and one received from a Dalamud upload:

Teamcraft:
```
> db.recentData.findOne({worldID: 74, itemID: 4990}).recentHistory[0].uploadApplication
FFXIV Teamcraft
> db.recentData.findOne({worldID: 74, itemID: 4990}).recentHistory.length
20
> new Date(db.recentData.findOne({worldID: 74, itemID: 4990}).lastUploadTime)
ISODate("2021-09-21T02:12:53.206Z")
```

Dalamud:
```
> db.recentData.findOne({worldID: 74, itemID: 5}).recentHistory[0].uploadApplication
goat
> db.recentData.findOne({worldID: 74, itemID: 5}).recentHistory.length
10
> new Date(db.recentData.findOne({worldID: 74, itemID: 5}).lastUploadTime)
ISODate("2021-09-23T02:02:53.941Z")
```

**Comment by daemitus** [comment]
@karashiiro Can you describe how the packets come in and what the new count packet is structed like, or how the debounce works?

We currently only read these 5 packet types:
- MarketBoardItemRequestStart
- MarketBoardOfferings
- MarketBoardHistory
- MarketTaxRates
- MarketBoardPurchase

[Dalamud\Game\Network\Internal\NetworkHandler.cs](https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/Network/Internal/NetworkHandlers.cs#L124)

**Comment by karashiiro** [comment]
Basically, the MarketBoardHistory packet is sent multiple times, with [20](https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/PacketDef/Zone/ServerZoneDef.h#L367-L385) entries in each packet. The MarketBoardItemListingStart packet [may have](https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/PacketDef/Zone/ServerZoneDef.h#L316) the precise number of listings and history entries in it, but otherwise (or even if so?) a 1-2 second debounce will capture everything in the burst. I'd show Teamcraft's debounce for reference, but [the code](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/apps/client/src/app/core/api/universalis.service.ts#L286-L311) has changed too much since I last looked at it, and I can't figure out how it captures all of the packets anymore. Maybe @Supamiu can explain that code better than I can.

Also, it's highly likely that this affects listings too - those should be handled in the same way.

**Comment by Supamiu** [comment]
Teamcraft doesn't even wait for all the packets to be here at all, it just reports the listings as they arrive from the server.

This way, nothing will be blocked and everything will be reported no mattter what.

The listener is setup like this: 

```ts
    this.ipc.marketboardListingHistory$.subscribe(packet => {
      if (this.settings.enableUniversalisSourcing) {
        this.handleMarketboardListingHistory(packet);
      }
    });
```

Which basically just says "when MarketboardListingHistory arrives, call the handler method"

And the handler just sends the report to Universalis, like this:

```ts
  public handleMarketboardListingHistory(packet: MarketBoardItemListingHistory): void {
    combineLatest([this.cid$, this.worldId$]).pipe(
      first(),
      switchMap(([cid, worldId]) => {
        const data = {
          worldID: worldId,
          itemID: packet.itemCatalogId,
          uploaderID: BigInt(`0x${cid}`).toString(10),
          entries: packet.listings.map((entry) => {
            return {
              hq: entry.isHq,
              pricePerUnit: entry.salePrice,
              quantity: entry.quantity,
              buyerName: entry.buyerName,
              onMannequin: entry.onMannequin,
              timestamp: entry.purchaseTime
            };
          })
        };
        return this.http.post('https://us-central1-ffxivteamcraft.cloudfunctions.net/universalis-publisher', data, {
          headers: new HttpHeaders().append('Content-Type', 'application/json')
        });
      })
    ).subscribe();
  }
```

**Comment by karashiiro** [comment]
That works for the extended history since that does a diff-and-merge on the server, but I don't think that works for the current data. The current data endpoint just shows the most-recently uploaded data, so if you're sending it as it comes along then you're repeatedly overwriting it with older and older data.

**Comment by Supamiu** [comment]
That's interesting, I might change that to aggregate and use a debounce to report everything at once 👍

**Comment by daemitus** [comment]
So what we have as a catalog Id in each individual listing is a "has more"
field actually. So you can loop through that for any history packet

**Comment by daemitus** [comment]
#680
