### ISSUE TITLE
SLI is incompatible with DXGI hooks

### ISSUE THREAD

**Issue by Drakonas** [goatcorp/Dalamud#60]
**Describe the bug here:**
When streaming using the Go Live feature in Discord, if FFXIV was launched using XIVLauncher, the entire feed jitters as if it's rendering then going back 2 frames, then going forward 4 frames, then back 2 frames, etc.

I have tried disabling XIVLauncher's Discord Rich-presence, Steam Integration, and In-Game additions... still doesn't fix it.

**Steps to reproduce the bug:**
1. Launch game with XIVLauncher.
2. Start Go Live stream in a Discord server voice-chat, select the game application "Final Fantasy XIV".

**Expected behavior**
Launches stream and the game flows normally.

**Screenshots**
[Video Link](http://mars.whatbox.ca:42424/img/2020-02-23_22-40-27.mp4)

**Other information (*please* complete the following information):**
  Operating System: Windows 10 1909
  XIVLauncher version: 4.7.2.0
  Launching as admin?: No
  Using Steam?: Launching XIVLauncher through Steam, but the game is not the Steam version.
  Addons/Plugins enabled: Reshade, various mods with TexTools, All other hooks in XIVLauncher disabled, but changing them does not change anything.

**Additional information**
Starting game vanilla without XIVLauncher works just fine with Discord Go Live.

I am using 2x GTX 1070's in SLI.

**Comment by goaaats** [comment]
I have no way of testing this and I don't think @ff-meli does either, so sadly we can't do any more testing on it for now.
I'll leave the issue open for now in case anyone with an SLI rig wants to take a look.

**Comment by goaaats** [comment]
If this still occurs, please let us know. I'll assume that it's fixed with api4.

**Comment by Drakonas** [comment]
I unfortunately do not have that rig anymore, so I couldn't tell you. :S Sorry.
