### ISSUE TITLE
Plugin installer category highlighting when searching is not consistent with actual results

### ISSUE THREAD

**Issue by chalkos** [goatcorp/Dalamud#615]
To reproduce:
1. Have QoL Bars installed
2. Search for QoL

There are no results, but the category is still highlighted

![unknown (1)](https://user-images.githubusercontent.com/98429/135724463-c2a27d40-ef85-4f82-9eb5-12bb694f2563.png)

**Comment by daemitus** [comment]
identified, pending PR
