### ISSUE TITLE
All plugins uninstalled themselves and can't be reinstalled

### ISSUE THREAD

**Issue by yuealice** [goatcorp/Dalamud#626]
![image](https://user-images.githubusercontent.com/92181288/136617661-4cc3b5c2-3e99-4f92-be0e-425300d5f715.png)
![image](https://user-images.githubusercontent.com/92181288/136618044-e1d73339-f616-4a8f-9f90-80f58632c570.png)
![image](https://user-images.githubusercontent.com/92181288/136617866-74c50962-b106-4f32-b262-d778cee906aa.png)
![image](https://user-images.githubusercontent.com/92181288/136618188-9d284d5e-c703-49f9-9d8b-612ff38214aa.png)

**Comment by goaaats** [comment]
Fixed now, please restart
