### ISSUE TITLE
Tier 1 Load issue

### ISSUE THREAD

**Issue by reiichi001** [goatcorp/Dalamud#642]
Some users are receiving T1 load errors for unknown reasons. They'd set their whitelists accordingly, redownloaded Dalamud, runtime, etc. Tried full uninstalls.

```
2021-10-11 14:45:58.346 -04:00 [ERR] Tier 1 load failed.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Reloaded.Hooks.Tools.Utilities' threw an exception.
 ---> System.Exception: Unable to find memory location to fit MemoryBuffer of size 65536 (69632) between 1 and 7FFFFFFF.
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Run[T](Int32 retries, Func`1 function)
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Allocate(Int32 size, Int32 minimumAddress, Int32 maximumAddress, Int32 retryCount)
   at Reloaded.Assembler.Assembler.AllocateText(Int32 textSize, Int32 retryCount)
   at Reloaded.Assembler.Assembler..ctor(Int32 textSize, Int32 resultSize)
   at Reloaded.Hooks.Tools.Utilities..cctor()
   --- End of inner exception stack trace ---
```

[dalamud (81).log](https://github.com/goatcorp/Dalamud/files/7324710/dalamud.81.log)

**Comment by breckdareck** [comment]
Looked online to see if I could find anything else related to the issue. Theres this thread, https://githubmemory.com/repo/xivdev/Penumbra/issues/51
In which the user had TexTools Mods and disabled and reenabled them. I tried the same (Since I had the Discord UI Mod Installed) with no joy.

Subbing to this issue since I am the one with this issue.

**Comment by breckdareck** [comment]
update: Completely Removed and Started over on TexTools. Ran integrity check on XIV came back with no issues. Still cannot get plugins to show.

**Comment by daemitus** [comment]
https://github.com/Reloaded-Project/Reloaded.Hooks/issues/12

I'm officially out of ideas.
