### ISSUE TITLE
XIVlauncher loads slowly, game starts slowly

### ISSUE THREAD

**Issue by grink** [goatcorp/Dalamud#652]
for some odd reason the quicklauncher has been taking very long to load. it's checking for updates and it takes like 3-4 minutes for the actual launcher to pop up. it only recently started doing this today. there's also no error message associated with this. also when i launch xiv through the launcher now, it goes unresponsive. it's also worth noting that throughout this the launcher also goes unresponsive.

after a long delay the game finally started in windowed mode.

 i was able to successfully launch it via quicklauncher when i randomly decided to launch it through the vanilla standard launcher, but  the game also now becomes unresponsive through the standard launcher. tried adding it to my windows defender whitelist and nothing changed.

noticed also there was a slight delay between the game launching when launching via the quicklauncher. started over via textools to make sure this wasn't some kind of weird error but no dice.

this issue has persisted through rebooting my computer as well. 

addenum: i do use gshade, installed it about a week ago, have not had any issues with xiv or the quicklauncher until yesterday. i did also did a clean sweep of all of my mods, which had no affect on the quicklauncher/game loading.

Specs
Windows 10 Education 64-bit

CPU
AMD K19

RAM
16.gb DDR4

Motherboard
ASRock x570 Steel Legend (AM4)

GPU
2047mb NVIDIA GeForce GTX 1660

**Comment by goaaats** [comment]
Hey, this doesn't seem to be an issue on our side, since it also happens when you use the official launcher. XL or Dalamud don't modify the game in any permanent way.
If you join our Discord, we can try to troubleshoot this further.
