### ISSUE TITLE
Add feedback configuration options

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/Dalamud#683]
Talked about across a few discord chats.

New Options (configured in manifest)
- Enable/disable feedback for plugin (enabled by default)
- Add feedback message to display on feedback screen (could use to list features that will never be added)
- Add custom feedback url (so developers could send to other discords for example)

Feedback Screen
- Show plugin feedback message if it's set.

Plugin Installer
- Show/hide the plugin feedback button depending if enabled/disabled.

Send Feedback
- If custom URL is set, use this instead (or in addition to?) the standard feedback url.

**Comment by goaaats** [comment]
I did everything in here but the custom URL, I think the repo url is fine for that
