### ISSUE TITLE
XIVLauncher is launching the game but crashing 4-5 seconds after getting to the main menu screen

### ISSUE THREAD

**Issue by holodrum** [goatcorp/Dalamud#695]
I've updated everything, the XIVLauncher is being ignored by my antivirus, etc.

The normal launcher is working without issues, only the XIVLauncher is crashing.

I saw a bunch of people mention it yesterday and earlier today on the discord server, but no solution, so I figured I would create an issue here.

**Comment by goaaats** [comment]
Hi, seems like you may have testing mode enabled for dalamud.

Could you try turning it off like this? 

https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-turn-dalamud-staging-on-or-off

**Comment by holodrum** [comment]
Hi, I appreciate the suggestion, but sadly that wasn't it, the "DoDalamudTest" was already set to false.

The only test thing I have enabled is "DoPluginTest", and setting that to false doesn't change anything either.
I even tried disabling Dalamud in the XIVLauncher settings, didn't help.

Is there anything else I can try, or should I just save my plugin settings folder and reinstall XIVLauncher?

**Comment by goaaats** [comment]
Does the official launcher work?

**Comment by holodrum** [comment]
Yeah, the official launcher works without any issues.

**Comment by holodrum** [comment]
I've tried reinstalling it a couple of times and also updated it, sadly it's still the same result.

I also still see people come into the Discord channel with the same issue (one posted about it as late as 30 minutes ago, but the post went unanswered).

Running without dalamud enabled changes nothing, but, running XIVLauncher as admin solves the issue, a solution another user posted in the discord, although a tester said that people shouldn't run it in admin, without explaining why not. Though, I do prefer not to run stuff unnecessarily as admin myself, so this isn't really a proper solution.

Is there anything I can do to test and determine what could be the cause?

**Comment by Aireil** [comment]
If you still have the issue, feel free to reopen.
