### ISSUE TITLE
Research dotnet/interactive, embed a c# shell in Dalamud?

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#706]
https://github.com/dotnet/interactive#notebooks-with-net

Maybe we can embed just the c# kernel in Dalamud, and expose the frontend through a Jupyter notebook?

**Comment by goaaats** [comment]
These are easy to embed it seems, though the price would be +60mb of dependencies.

We could...
- Implement it as a hidden plugin that devs can install?
- Some other way to download the dependencies for it?
- Have a separate Dalamud distribution for devs?
- Only include it in debug builds? (would probably be useless then)

**Comment by goaaats** [comment]
I've started implementing this as a plugin that can be installed by Dalamud when needed, containing dependencies.

**Comment by daemitus** [comment]
I remember when I tried to do this back when we were discussing it. the
dependency size is no joke, atleast for that method.

**Comment by goaaats** [comment]
Yeah, the scripting + compiler dependencies amount to at least 70mb. There's (at least one) plugin(s) bigger than that, so it should be alright, if not we can always improve plugin downloads, in case we notice an obvious issue.
