### ISSUE TITLE
Enhancement: Include obvious way to update plugins at the startup screen

### ISSUE THREAD

**Issue by Eternita-S** [goatcorp/Dalamud#747]
Currently, there is no obvious way other than clicking invisible button and going to installer from there to update plugins before logging into game/know that there are plugins that require update.

Considering automatic plugin updates are disabled by default, it may very easily lead to a situation where end user simply misses out new/enhanced features and fixed bugs for quite a while or simply just keeps outdated plugin version for a while until game updates and it starts malfunctioning. And chat message is actually easy to ignore.

What I would suggest is that if plugin updates are available, display a menu bar before user is logged in that would contain "You have outdated plugins" message together with "Open plugin installer" button.

**Comment by goaaats** [comment]
I was working on an API for this but shelved it, may be a good idea though

**Comment by goaaats** [comment]
Done with title screen menu
