### ISSUE TITLE
Adjustable spacing of server info bar UI?

### ISSUE THREAD

**Issue by hibiyasleep** [goatcorp/Dalamud#751]
Recently I found a plugin Orchestrion moved into Server Info Bar UI (not complaining about plugin!).

however, after this update, the spacing between Orchestrion and existing items has been significantly grown, I except this is for isolating third party elements from original one but I want to do exactly opposite of this. (even wanted before this update, but it was endurable)

tldr: Can this be customized?

![image](https://user-images.githubusercontent.com/5380174/152104901-0c5bbb23-864a-48b9-9f6b-5f82e5f41fcc.png)
![image](https://user-images.githubusercontent.com/5380174/152105028-ccc399c0-549d-45e3-89c1-79082e8da402.png)

**Comment by goaaats** [comment]
Yup, I'll probably add it later today or this week
