### ISSUE TITLE
Game crash in the installer

### ISSUE THREAD

**Issue by Aireil** [goatcorp/Dalamud#753]
AccessViolation, seems random, got it in like 2 launches out of 10.
To reproduce, open the game, and open the installer (I went in changelog and scrolled fast, not sure if that matters).

![vs](https://user-images.githubusercontent.com/33433913/152473695-ffc7f307-de6a-4b5c-80f9-4403b5a90088.png)
ImGuiScene.dll!ImGuiScene.RawDX11Scene.CreateTexture(void* pixelData, int width = 512, int height = 512, int bytesPerPixel) Line 226
 	ImGuiScene.dll!ImGuiScene.RawDX11Scene.LoadImage_Internal(StbiSharp.StbiImage image) Line 202
 	ImGuiScene.dll!ImGuiScene.RawDX11Scene.LoadImage(byte[] imageBytes) Line 178
 	Dalamud.dll!Dalamud.Interface.Internal.InterfaceManager.LoadImage(byte[] imageData) Line 262
 	Dalamud.dll!Dalamud.Interface.Internal.Windows.PluginImageCache.DownloadPluginIconAsync.__TryLoadIcon|37_0(byte[] bytes, string loc = "https://raw.githubusercontent.com/goatcorp/DalamudPlugins/api5/plugins/WheresWOLdo/images/icon.png", Dalamud.Plugin.Internal.Types.PluginManifest manifest = {Dalamud.Plugin.Internal.Types.RemotePluginManifest}, Dalamud.Interface.Internal.InterfaceManager interfaceManager, out ImGuiScene.TextureWrap icon = null) Line 244
 	Dalamud.dll!Dalamud.Interface.Internal.Windows.PluginImageCache.DownloadPluginIconAsync(Dalamud.Plugin.Internal.LocalPlugin plugin = null, Dalamud.Plugin.Internal.Types.PluginManifest manifest = {Dalamud.Plugin.Internal.Types.RemotePluginManifest}, bool isThirdParty = false) Line 318

**Comment by goaaats** [comment]
Should be fixed in https://github.com/goatcorp/Dalamud/commit/0fdacadc84097aeb0dfd87875a807dc20277ea12, I added error handling anyway just in case we notice it again
