### ISSUE TITLE
(DtrBar) Calling Entry.Remove() does not actually removes the entry on the title screen

### ISSUE THREAD

**Issue by xorus** [goatcorp/Dalamud#759]
When I reload my plugin from the title screen, it crashes with the "An entry with the same title already exists.".

However I am properly callling DtrBarEntry.Remove() when disabling my plugin (and I can reload the plugin just fine when logged in-game)

I'm just doing `_entry = dtrBar.Get("EngageTimer stopwatch");` in my constructor and then `_entry.Remove();` in Dispose. I have confirmed that the dispose works properly by logging something on dispose (and DtrBarEntry.ShouldBeRemoved does get set to true).

I think the issue is somewhere around here :

https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/Gui/Dtr/DtrBar.cs#L124

As the DtrBar does not exist, the program does not remove the entry from it's dictionnary when I'm unloading my plugin, causing an error when I try to reload it.

Is this something you can fix or should I just try/catch it and re-attempt to Get() every frame until it works?

**Comment by karashiiro** [comment]
I'm also having this problem, I've been working around it by attempting to create it repeatedly with slightly different names: https://github.com/karashiiro/PingPlugin/blob/b168ee9827b8484c2440cc6658679d16051b9ebd/PingPlugin/PingUI.cs#L48-L70
