### ISSUE TITLE
IPC SendMessage breaks with null parameters

### ISSUE THREAD

**Issue by ascclemens** [goatcorp/Dalamud#760]
Here's why:
https://github.com/goatcorp/Dalamud/blob/53489fd810309c5f017419386c3d1f82cb496cb0/Dalamud/Plugin/Ipc/Internal/CallGateChannel.cs#L116

I'm not sure how this should be fixed, otherwise I'd PR.

**Comment by goaaats** [comment]
Probably best to just pass null through to subscribers.

**Comment by ascclemens** [comment]
I'm confused.

```cs
internal void Invoke(string id, PlayerPayload? sender, ulong contentId, Payload? payload) {
    this.InvokeGate.SendMessage(id, sender, contentId, payload);
}
```

If either of those nullable types are actually null, subscribers will never get the message because they're null and that exception throws.

**Comment by goaaats** [comment]
Pushed a fix, please close if it works - allows null for reference types, requires a value for value types
