### ISSUE TITLE
Changelog and string formatting - crash

### ISSUE THREAD

**Issue by Kherae** [goatcorp/Dalamud#763]
currently, maplinker's live version includes %s in the changelog string. The result? Hard CTD without error.  Dalamud might need to sanitize the strings before attempting to use them.

**Comment by Bluefissure** [comment]
> currently, maplinker's live version includes %s in the changelog string. The result? Hard CTD without error. Dalamud might need to sanitize the strings before attempting to use them.

Sorry about this, didn't know it was crashing the changelog window.

> Fixed, thanks

Glad to see the fix.
