### ISSUE TITLE
Font size in Dalamud settings not readable.

### ISSUE THREAD

**Issue by btofnc** [goatcorp/Dalamud#799]
The font in Dalamud settins ui is too blurry to read. When I set the font size to bigger, it will be blurry. When I set it smaller, it will be clear but not readable.

Here are the screenshots
[https://imgur.com/a/dhhwBBL]

**Comment by lincTHU** [comment]
![image](https://user-images.githubusercontent.com/8018928/163998474-a83f1bbf-ec00-4671-a485-49e3acda3eb7.png)
same problem

**Comment by kyaroru0203** [comment]
![image](https://user-images.githubusercontent.com/104076240/164231888-c8072a23-4302-44e0-81f5-dd6096847866.png)
same problem too.
eventhough I reinstall it.

**Comment by lincTHU** [comment]
Hey I found a solution works for me
Toggle [usx AXIS font] and click save. It works for me. 
If it doesn't work, try a higher font resolution level.
![image](https://user-images.githubusercontent.com/8018928/164443667-62ffb531-5ca6-4692-bb86-d8388372da65.png)

**Comment by goaaats** [comment]
Hey, sorry folks, that workaround is indeed recommended. We have some great improvements to font rendering in the pipeline thanks to a dedicated volunteer, so I hope we'll get this solved for good soon.

**Comment by btofnc** [comment]
> Hey I found a solution works for me Toggle [usx AXIS font] and click save. It works for me. If it doesn't work, try a higher font resolution level. ![image](https://user-images.githubusercontent.com/8018928/164443667-62ffb531-5ca6-4692-bb86-d8388372da65.png)

sad...this not work for me..
