### ISSUE TITLE
XIVLauncher attempting to start invalid .NET runtime

### ISSUE THREAD

**Issue by kaitan32** [goatcorp/Dalamud#817]
Long story short, I broke my .NET runtime installation messing around with an unrelated application, and since then I can't Dalamud to recognize any custom repositories. I've done my best to figure out the issue on my own, but this is where I've gotten stuck: output.log indicates that it's trying to start .NET 6.4.0.6, but that fails. Instead of redownloading, it then tries to start for .NET 5.0.6, which I no longer have on my machine according to a dotnet --list-runtime command.

I tried removing all relevant files and registry keys followed by a reinstall, but with the same result: the quicklauncher works fine, I just can't get Dalamud to recognize the Penumbra repository after pasting, enabling, and save/close.

Any suggestions as to where I should go from here?

[dotnet --list-runtime results](https://user-images.githubusercontent.com/26716985/164942925-21af7c2a-e2f4-4d8c-9e17-906ed9431a9e.png)
[output.log](https://github.com/goatcorp/Dalamud/files/8548406/output.log)

**Comment by goaaats** [comment]
Dalamud doesn't use the OS-level .NET runtime at all, it ships its own version of .NET 5.

Make sure that you are pasting the URL into the "third party repositories" list and not into the "developer plugins" list.

**Comment by kaitan32** [comment]
I have it in the "custom plugin repositories" section, which I think is the same thing? It's marked as enabled but not listed in my Installed Plugins
[Plugin settings](https://user-images.githubusercontent.com/26716985/164943715-5f00a226-1674-4f82-9dbe-f658468e42cc.png)

**Comment by kaitan32** [comment]
I see - I thought Penumbra would be listed there provided I had it included and enabled in the custom repository list.

I'll approach this from the Penumbra side and see if I can get it sorted out. Thanks for the help!
