### ISSUE TITLE
Disable plugins without uninstalling them

### ISSUE THREAD

**Issue by rootdarkarchon** [goatcorp/Dalamud#836]
Like the title suggests, I'd like to see an option to disable the plugin without uninstalling them. 
This is a feature already present for dev plugins and I would like to see it for normally installed plugins as well.

The main benefit would be to be able to disable plugins and still have them in the installed list, ready to be toggled on again on demand without having to look through the main repo for the plugins you have disabled (i.e. for testing purposes).
I can see both 'Disable' and 'Uninstall' for a plugin where the latter would take the functionality of the current 'Disable' and the new 'Disable' would just be an unload toggle, like the dev plugin unload.

On a side note: the current plugin 'Disable' deleting the plugin after a game restart is not very intuitive and unexpected behavior from a 'Disable' button.

**Comment by kalilistic** [comment]
There's an open discussion right now about a plugin installer refresh/overhaul. I'd add this as a consideration there.

**Comment by rootdarkarchon** [comment]
Thank you for considering this. Looking forward to the refresh/overhaul.
