### ISSUE TITLE
Is it possible to Send Chat Massages to Game?

### ISSUE THREAD

**Issue by michaelcurry** [goatcorp/Dalamud#862]
First off, If this is the not the correct location for a questions like this, please feel free to redirect me.

I am developing a Chat plugin, but am having issues figuring out how to send messages to chat channels (Example: Say, Yell, FC, LS1, etc.).  I thought using `ChatGiu.PrintChat()` would work, but it looks like this only displayed the information on my local client, and the message is not sent out to the game servers.  Any help would be much appreciated. 

**Current Code**
```
if (ImGui.InputText("###ChatChannelInput", ref inputBufferMessage, 500, inputFlags, InputBufferCallback))
{
    var outboundMessage = new XivChatEntry
    {
        Type = ActiveChannel!.Type,
        SenderId = Service.ClientState.LocalPlayer!.NameId,
        Name = Service.ClientState.LocalPlayer.Name,
        Message = SeString.Parse(Encoding.UTF8.GetBytes(inputBufferMessage.Trim()))
    };
    
    Service.Chat.PrintChat(outboundMessage);
}
```

ChatGiu.PrintChat() Documentation: https://goatcorp.github.io/Dalamud/api/Dalamud.Game.Gui.ChatGui.html#Dalamud_Game_Gui_ChatGui_PrintChat_Dalamud_Game_Text_XivChatEntry_

**Comment by goaaats** [comment]
We don't implement this, as such an API would be very easily abused, be it intentionally or unintentionally. The documentation definitely could be more explicit.

**Comment by NotNite** [comment]
Once https://github.com/goatcorp/faq/pull/48 gets merged, I'll add that to the Developer FAQ if you want @goaaats?

**Comment by michaelcurry** [comment]
@goaaats: That makes total sense, unfortunate, but 100% understandable.

**Comment by goaaats** [comment]
Closing this, feel free to reach out for any further questions.
