### ISSUE TITLE
Getting error code 0xc0000005. Access violation detected in coreclr.dll

### ISSUE THREAD

**Issue by CSeriesJTYPE** [goatcorp/Dalamud#864]
Game will crash with the same error consistently on area transition, and I had one instance where it happened loading Penumbra with the chat shortcut. Tried to narrow this down by removing every plugin but Penumbra, still happened. Is this a known issue?

EDIT: Sorry I believe I should have posted this under the XIVLauncher issues page.

**Comment by NotNite** [comment]
Is this still happening? Does it happen without plugins?
