### ISSUE TITLE
Installed plugin shows it's internal name in plugin installer instead of public name

### ISSUE THREAD

**Issue by Limiana** [goatcorp/Dalamud#866]
Like this
![TJBR31jgxf](https://user-images.githubusercontent.com/5073202/171615899-86f96ce4-96e3-41b4-9e97-2883f74edc5d.gif)

**Comment by PunishedPineapple** [comment]
I'm pretty sure it uses the `IDalamudPlugin.Name` implementation from the plugin when the plugin is actually loaded.  I had this issue with some of mine, and it ended up being that I didn't set that interface member to what I should have.  Whether that's ideal behavior for the plugin installer or not, idk.

**Comment by Eternita-S** [comment]
Isn't `IDalamudPlugin.Name` - internal plugin's name? Changing it would break updates and so I'd imagine

**Comment by Aireil** [comment]
`IDalamudPlugin.Name` is basically never used these days. I'm guessing that issue is solved, if not, feel free to reopen it.
