### ISSUE TITLE
DIP17/Dalamud: load DalamudPackager output zips

### ISSUE THREAD

**Issue by philpax** [goatcorp/Dalamud#868]
This issue assumes https://github.com/goatcorp/DIPs/pull/38 is merged.

Dalamud should be able to load plugin ZIPs, consisting of the plugin's DLL, a `plugin.json`, and any dependencies. It should not need to be pointed at individual files. This should also resolve the issue with the dev plugin loader not being able to source the metadata for a plugin, as now the ZIP it loads should have everything it needs.

**Comment by goaaats** [comment]
Solved in xlweb, though we still have that possible "temporarily load zipped plugins by dragging them in" idea for testing, not sure if we should still target that

**Comment by philpax** [comment]
That was desired by a few folks, especially developers cross-testing each others' plugins. I'll keep this issue open and rename it to reflect that.
