### ISSUE TITLE
DIP17/GitHub Actions: new PR behaviour

### ISSUE THREAD

**Issue by philpax** [goatcorp/Dalamud#869]
When a new PR is made to `DalamudPluginManifests`, the following should happen:

- grabs existing manifest from HEAD if it exists
- automatically rejects the PR if the PR submitter is not within the existing `owners` array
- blocks merge until approval by a member of the review team

**Comment by goaaats** [comment]
QoL: Post a link to a diff in the description

**Comment by philpax** [comment]
> QoL: Post a link to a diff in the comments

should be covered by https://github.com/goatcorp/Dalamud/issues/870#issue-1259003744
