### ISSUE TITLE
Implement a more robust SeString API

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#87]
- [x] Implement Lumina DI to resolve payloads that depend on game data

TextPayload:
- [x] Handle special unicode characters

ItemPayload:
- [x] Switch resolve to Lumina once ready, should not be using XIVAPI anymore

**Comment by ff-meli** [comment]
These specific items are basically done in #100 (and other code for the special characters), but I'll leave this open since there's a fair bit more to do to make things nicer.

**Comment by goaaats** [comment]
Thanks Meli
