### ISSUE TITLE
DIP17: Tracking issue

### ISSUE THREAD

**Issue by philpax** [goatcorp/Dalamud#874]
This issue tracks the status of all work required for DIP17. Once everything here is complete, DIP17 is officially 'done' and deployed.

- **Dalamud:**
    - https://github.com/goatcorp/Dalamud/issues/868
- **DalamudPackager:** (depends on Dalamud)
    - https://github.com/goatcorp/Dalamud/issues/867
- **GitHub Actions:** (depends on DalamudPackager)
    - https://github.com/goatcorp/Dalamud/issues/873
    - https://github.com/goatcorp/Dalamud/issues/869
    - https://github.com/goatcorp/Dalamud/issues/870
    - https://github.com/goatcorp/Dalamud/issues/871
    - https://github.com/goatcorp/Dalamud/issues/872

**Comment by philpax** [comment]
@goaaats did some great work on the build agent here; looks like it just needs to be brought across the line: https://github.com/goatcorp/Plogon

Aside from that, I think we should try to get #867 and #868 done, so that we can start getting the ecosystem ready and set the groundwork for #892 (especially so that people can load plugin zips without having to yeet files into devplugins or create folders.)

Would anyone from @goatcorp/dalamud be able to take on those two tasks? (Anyone else is of course welcome, but make sure to check in with the team to make sure you're on the same page)

**Comment by philpax** [comment]
@goaaats are #868 and #867 complete / can we close this out?

**Comment by goaaats** [comment]
Yes, both of these are done, thanks for keeping track
