### ISSUE TITLE
Wrong values on some MapLinks

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#88]
When the value of RawX and RawY are technically supposed to go into the negative, instead, since they are interpreted as uints, the value shoots up:
![image](https://user-images.githubusercontent.com/16760685/79903391-47149e00-8413-11ea-9a10-a8c7fdf2cf56.png)

Steps to reproduce:

1. Go to Lakeland
2. Go to X: 20.9 Y: 21.0 Z:0
3. Send an ``/e <pos>`` and log the value of the produced MapLinkPayload

Is this a bug?
This was previously attempted to be fixed by #84.

**Comment by ff-meli** [comment]
There is no issue with that - they are raw values, which are essentially only meaningful as a hex/bit pattern.  The resolved values will map as expected.

**Comment by ff-meli** [comment]
for instance, those values in your screenshot decode to (20.98374, 21.0252), which in game is then truncated at one decimal to (20.9, 21.0) - exactly the location you specified

**Comment by goaaats** [comment]
Alright, thanks for clarifying!
