### ISSUE TITLE
Require contact info for feedback

### ISSUE THREAD

**Issue by NotNite** [goatcorp/Dalamud#894]
We get wayyyyyy too many feedbacks without contact info, rendering them useless. We should also tell the user not to include character names as feedback.

**Comment by reiichi001** [comment]
Proposal: Add a feedback type selector box.
- Feature Request -> contact optional
- Bug - contact optional
- Request for Help -> remind user to use a valid email and/or be in Goat Place discord

**Comment by NotNite** [comment]
This has (sort of) been implemented in #932. I'm happy with this feature - closing.
