### ISSUE TITLE
"Disabling plugin..." Installer Overlay Stuck On

### ISSUE THREAD

**Issue by PunishedPineapple** [goatcorp/Dalamud#929]
When disabling a plugin and it errors, the installer overlay for "Disabling plugin..." stays there indefinitely.  Yes, obviously a plugin shouldn't throw during disposal (something else seems to be fucky, because toggling a UI node causes an access violation, but it wouldn't be toggling if the addon+node didn't exist; that's irrelevant to this, though), but plugin installer becomes unusable as a result and you have to restart.

**Comment by Aireil** [comment]
Fixed in #927
