### ISSUE TITLE
Reload plugins cause infinite game freeze

### ISSUE THREAD

**Issue by Pythyu** [goatcorp/Dalamud#940]
I used to profit from the reload plugins feature quite a bit but since around patch 6.18 reload plugins make my game freeze infinitely. Is it only me ?

**Comment by NotNite** [comment]
Regular plugin users should not be reloading plugins - this is a developer tool.

**Comment by reiichi001** [comment]
Can you provide more detail on why you were using that feature? It's hidden in the dev menu and should basically never be used by a user.

If you're doing plugin development work, you can set Dalamud to reload specific plugins on change.

Telling it to do the entire list of installed plugins is usually a surefire way of triggering a plugin unload error, or to load a plugin later than it's supposed to.

**Comment by Pythyu** [comment]
Yea was for development.

Ngl i had some weird ui bug when i tried at first to setup with the dev folder for development and at the time was a bit lazy so I discovered that i could just build my project replace file in installed plugin and reload (i know it's very bad and not made for that purpose) but it worked well for quite a time xD just recently i can't do it anymore

**Comment by NotNite** [comment]
Absolutely do not do that. Set a dev plugin folder to your build directory in the Dalamud settings, and set the dev plugin to auto reload.

**Comment by Pythyu** [comment]
Yea i know, but now the thing is even without touching anything so no replacing file bullshit and all just reloading plugins alone is lopping infinitly looping my game

**Comment by NotNite** [comment]
Does this happen without your dev/third party plugins? Does this happen with all plugins uninstalled?

**Comment by Pythyu** [comment]
It does happen even without my dev but didn't try to uninstall all the plugins i used

**Comment by Pythyu** [comment]
Is disabling enough or i should hard clean up uninstall remove file in installed and remove config files ?

**Comment by Pythyu** [comment]
For now my observation is when i disable them all i can reload without any issue since he has nothing to reload but as soon as I try to reload with one plugin enabled (any) it freezes

**Comment by reiichi001** [comment]
Starting around Dalamud 6.4.0.40, we made a number of changes to how Dalamud can load plugins, some which really are not designed to be triggered after the game is already running. 

The "reload all plugins" option in the dev menu is a carry over from Dalamud being written for .Net Framework, which had several differences in how plugins were loaded. 

It should not be used anymore. There is nothing more to discuss. Please do not use that feature.
