### ISSUE TITLE
My Dalamud isnt letting me try to fix it. but it will let me use only penumbra

### ISSUE THREAD

**Issue by Arkhams087** [goatcorp/Dalamud#967]
im new to this stuff sorry, and my dalamud is not allowing me to uninstall what ever could be the prob, i uncecked all the boxes to see if that work but nothing seems to fix it

![image](https://user-images.githubusercontent.com/111726548/185847200-1fa97026-5879-4929-8f69-d88f8653a371.png)
![image](https://user-images.githubusercontent.com/111726548/185847239-d14a9849-fd34-451d-bb17-8bcdc183d123.png)

**Comment by Arkhams087** [comment]
/mare, /glamourer, /ppeep isnt working at all
noting

**Comment by NotNite** [comment]
We do not provide support for third party plugins.
