### ISSUE TITLE
Dalamud Error

### ISSUE THREAD

**Issue by Equinox1906** [goatcorp/Dalamud#968]
Hello,
my game keeps crashing on startup (shows a dalamud error). only when i launch without plugins it works.
Can someone help me figure out which plugin is responisible for the crashes?
I have even removed all Texttool plugins and gshade so it should be a dalamud mod.
[dalamud_appcrash_20220822_170438_966_10188.log](https://github.com/goatcorp/Dalamud/files/9395501/dalamud_appcrash_20220822_170438_966_10188.log)
[dalamud.log](https://github.com/goatcorp/Dalamud/files/9395504/dalamud.log)

**Comment by NotNite** [comment]
Please remove your third party plugins.

**Comment by Equinox1906** [comment]
? they are removed only dalamud and quicklauncher are left. or do you mean the dalamud plugins?

**Comment by NotNite** [comment]
Third party plugins.

**Comment by Equinox1906** [comment]
what are third party plugins for you?

**Comment by NotNite** [comment]
Plugins you install by adding custom repositories. We do not provide support for them and cannot help you if you have them installed.

**Comment by Equinox1906** [comment]
so this includes also the plugins installed through dalumud?

**Comment by reiichi001** [comment]
> so this includes also the plugins installed through dalamud?

Any plugin that has the yellow [3] on its icon, which isn't part of our official plugin repository. Based on your dalamud log, that includes:
```
AntiAfkKick-Dalamud - 2.1.0.1
XIVAuras - 0.2.3.1
```

"Third party plugins" is what we call plugins that you've added that are outside of our support. While most of them are probably fine, many don't follow the plugin guidelines and we have no means of supporting them. 

Based on your crash log, it looks to be something font-related. It may help to disable plugins that make use of additional fonts as well. 

If you're not sure what these are, I would recommend the following.
1. Disabling all your plugin. 
2. Enable half of the disabled plugins back and test.
3. If the issue isn't happening, enable half again and repeat.
4. if the issue happens again, disable half of those, and retest.
5. Repeat steps 3 and 4 until you can find which plugin is causing the issue.

**Comment by Equinox1906** [comment]
ok ill try

**Comment by AimmePuff** [comment]
Hi I'm quite new to this - I am having the same issue and have tried out the advice above but still get met with the same error message no matter what I do. Have taken some screenshots and I also ran an integrity check (have attached a pic of the report). I have textools uninstalled and no files on that either. 
![error message](https://user-images.githubusercontent.com/112999020/190040632-daf77412-0505-47d3-824d-761bf5188346.PNG)
![missing](https://user-images.githubusercontent.com/112999020/190040636-a69cf958-acce-4933-b455-806e8eef1a13.PNG)

**Comment by Equinox1906** [comment]
ok issue was with quicklauncher i send their mods on discord a dump file and they fixed it.
