### ISSUE TITLE
Controller not being located.

### ISSUE THREAD

**Issue by Prince-Lanval** [goatcorp/Dalamud#970]
Hello, I've noticed recently that my controller has been acting up recently in FF and I believe Dalamud is preventing the FF client from finding or holding a stable connection with it. Problems like inputs being eaten or movement that acts like the controller was disconnected so I run in a straight line until it reconnects and issues like that. Originally I thought it was my controller so I swapped out the wire to my PC, swapped which DS4 controller I was using, and even tried Bluetooth connections but it's only gotten worse and worse. With this most recent Dalamud update it just straight up wont find the controller or if it does, it doesn't let the FF client see any of the inputs. I'm assuming it's the Dalamud client as when I try other games that use controller on my PC or even use the base FF client and it finds the controller and works just fine. Other than uninstalling and reinstalling, I don't know what else I could possibly do to fix the problem.

**Comment by NotNite** [comment]
How are you sure this is a Dalamud issue? Have you tried without Dalamud but using XIVLauncher? Do you use Steam?

**Comment by Prince-Lanval** [comment]
I believe it is a dalamud issue because with the normal XIVLauncher has no problems finding and letting me use my controller nor does steam have a problem finding it (I don't have FF connected to steam as I heard horror stories from friends that did and decided to not do that). About a month ago I realized that it'd go almost all the way through loading into the game from character selection for my controller to even respond. Sometimes it'd just stop in the middle of raid or roulettes but come back seconds later. But now it wont even see it and that only started happening after an auto update that happened a few days ago.

**Comment by NotNite** [comment]
Just to confirm, you went into the XIVLauncher settings, disabled Dalamud, launched the game using XIVLauncher (not the official launcher!), and the controller worked fine?

**Comment by Prince-Lanval** [comment]
Ahh, I originally just used the official launcher and was talking about that (I didn't realize the launcher with Dalamud was called the XIVLauncher. I've always just called it the Dalamud Launcher to my friends.) but I just went into the the XIVLauncher setting and launched with Dalamud disabled and my controller was spotted immediately and works just fine.

**Comment by NotNite** [comment]
Does this still happen if you uninstall your plugins, but keep Dalamud enabled?

**Comment by Prince-Lanval** [comment]
No. With all 31 of my plugins in my plugins folder removed, my controller works just fine which means it's probably a plugin acting up and I'm going to have to find which one. Thanks for helping me troubleshoot!

**Comment by NotNite** [comment]
No problem! I'll be closing this issue - if you're still having issues feel free to re-open. Good luck figuring out the misbehaving plugin!
