### ISSUE TITLE
Gauge bar values (Ninja)

### ISSUE THREAD

**Issue by telinit** [goatcorp/Dalamud#978]
Hey. It seems that ninja gauge bar values are broken after the 6.2 update. I use DelvUI and it shows wrong numbers:

![image](https://user-images.githubusercontent.com/4019549/186893035-01c89743-95c0-490a-b3ef-a91bda5a1571.png)

I turned on the developer mode and looked into the gauge struct's values:
![image](https://user-images.githubusercontent.com/4019549/186891351-762ad33f-7816-48aa-a322-8bddbb1cefc2.png)

Then I followed the address in my debugger (x64dbg) and here's what I saw:
![image](https://user-images.githubusercontent.com/4019549/186893169-cc2c28b8-6ecb-4887-b0aa-d2bfca19e4a2.png)

I believe, `HutonTimer` value from `NinjaGauge` [struct](https://github.com/goatcorp/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs#L164) should be ushort (2 bytes) now, not int (4 bytes) and other fields should have their offsets changed accordingly.

I'm not sure how can I test this change if I build Dalmud from the sources. How do I use my own local version instead of the FFXIVLauncher's own which it downloads and installs automatically?

Anyway, I hope the info above helps to fix this bug.

**Comment by yurisim** [comment]
Poohky made changes to client structs here

https://github.com/aers/FFXIVClientStructs/commit/537b6a60467d204ff2d72ef36d1a08dc17a2c9a8

That addresses this. Apparently we just got wait for dalamund to incorporate the new client structs.
