### ISSUE TITLE
Dev plugins do not appear to be working at all

### ISSUE THREAD

**Issue by SpuriousSnail86** [goatcorp/Dalamud#979]
I have upgraded the .NET framework version to 6.0 and rebuilt my plugins 

I am still getting the error in the attached screenshot after rebuilding and reloading them from "devplugins" folder (which was previously working)

![god](https://user-images.githubusercontent.com/60520448/186970254-61ef0d79-ec70-4dac-b161-1d6496ba507a.PNG)

**Comment by SpuriousSnail86** [comment]
updated the API level to 7 in plugin manifest and it did not solve the problem sadly

**Comment by Infiziert90** [comment]
You have to restart, else the manifest will not get parsed again

**Comment by SpuriousSnail86** [comment]
Restart PC or the game? I restarted the game

**Comment by SpuriousSnail86** [comment]
I have uploaded the plugin to a private github repo. and it now installs. but shows this trying to load the plugins (the plugins were all compiled without errors)

![hmmmmmmm](https://user-images.githubusercontent.com/60520448/186978320-3d106197-e543-40eb-956c-eecffcf11fad.PNG)

**Comment by NotNite** [comment]
You probably just messed something up with your repository. You do not need a custom repository to load plugins. Please ensure your plugin's manifest is API 7 in the compiled output.

**Comment by SpuriousSnail86** [comment]
now this appears

![image](https://user-images.githubusercontent.com/60520448/186980427-f44482cb-f14b-4ce9-996f-396d75fc021d.png)

**Comment by SpuriousSnail86** [comment]
which is nonesense because it does inherit from IDalamudPlugin

**Comment by NotNite** [comment]
Please join the development channels in our Discord server (https://goat.place/). It's easier to troubleshoot there than GitHub.
